### ISSUE TITLE
?? function is not well handling undefined values

### ISSUE THREAD

**Issue by Oldes** [red/red#1103]
red>> ?? foo
    foo: *** Script error: probe does not allow unset for its value argument
    *** Where: probe

I will post a fix soon.

**Comment by Oldes** [comment]
Now the result will be:

    red>> ?? foo
    foo: undefined

**Comment by Oldes** [comment]
The output from ?? function is not useful much as it does not handle new-lines of the original, but anyway, with this little change it does not throw error where it's unnecessary.

**Comment by Oldes** [comment]
But when I think about it, maybe it would be better to fix `probe` to return "unset!" if `unset!` is in its input.

**Comment by dockimbel** [comment]
About `unset!` support for PROBE, it would slowdown PROBE which is heavily used for debugging, so I think that the performance hit overweights the very rare cases where you would like it to support `unset!` values.

About your proposition, what happens if your word's value is the string "undefined"? :-) Maybe it would be better to display simply "unset!", so that it matches the result of MOLD on an unset value.
