### ISSUE TITLE
red/console ESC key to terminate running code, exit from multiline edits

### ISSUE THREAD

**Issue by x8x** [red/red#1122]
Sometimes we do mistakes in code and generate infinite loops, it would be nice if the `ESC` key would terminate running code in the console.

In this case:
```rebol
red>> parse {12^/34^/56} [collect some [keep to [lf skip | end]]]
^[^[^[^C%
```
pressing ESC key will print `^[` in the console, `CONTROL-C` will be needed to terminate the console.

here:
```rebol
red>> [
[    ;press ESC nothing happen
[    ]
== []
```
I would assume that we could return to prompt with `ESC` after the open bracket, but have to match open brackets with closing brackets to return to prompt.

**Comment by dockimbel** [comment]
It is not a good solution to use ESC or any other key to interrupt a native code loop like that one used in Parse. If we added support for that, we would need to check for the key stroke on every native loop, totally killing the performances.

Though, ESC key could be implemented in the interpreter to exit from Red-level loops, but still it might not work 100% of the time.

**Comment by dockimbel** [comment]
For the empty block issue, it works well in the DOS console, but not on Linux.

**Comment by dockimbel** [comment]
Let me know if it works fine now on Mac OSX too.

**Comment by x8x** [comment]
All good, escaping now. Wondering, with an open bracket, `CONTROL-C` does't do anything, is that by design? Or should it always exit the console?

**Comment by x8x** [comment]
Re: "Though, ESC key could be implemented in the interpreter to exit from Red-level loops, but still it might not work 100% of the time."

I think in the console it should! After all, in the console we are either testing code or manually handling stuffs (red/console as a shell..) . In both cases losing the context of the console is worse then a small hit in performance.
Not sure but wouldn't be possible to query the system keys buffer only once every second instead of in every native loop?

**Comment by dockimbel** [comment]
_Not sure but wouldn't be possible to query the system keys buffer only once every second instead of in every native loop?_

You can query that, but there are still no way to interrupt the native loops when you want. Anyway, as I said, it might not work 100% of the time, but it should work fine 99.99% of it. ;-)

**Comment by x8x** [comment]
Please add it to feature requests list. Thank you!

**Comment by mydoghasworms** [comment]
@dockimbel I'm not sure I understood this discussion correctly, but it would be useful in the console to be able to interrupt any running process. 

In the Rebol console, you can interrupt a process with the Escape key. E.g. the following infinite loop will be interrupted with the Esc key:

`while [true] []`

Currently in the Red console, Esc does not interrupt the execution. At least in Windows; you have to kill the process. (I thought that's what this issue was originally logged about, but maybe I missed something?).

**Comment by xqlab** [comment]
maybe there can be a system/console/break flag as in Rebol, that determines, if you can break or not.
