### ISSUE TITLE
Two questions about parent-types and inheritance

### ISSUE THREAD

**Issue by meijeru** [red/red#1203]
The first one is already in #1202, but it really belongs here.

* `map!` is implemented using the representation structure `red-hash!` but its parent type is not`hash!` --- is there no inheritance to be gained?
* `function!` has parent type `context!` but there are no actions specified as inherited -- what is the gain?

**Comment by dockimbel** [comment]
`map!`: no there is nothing we can re-use from the `hash!` datatype implementation, `map!` is namespace-oriented, `hash!` is array-oriented.

`function!`: I guess it was just an early assumption that some features could be inheritated, but not so far (though, that may change in the future).

**Comment by dockimbel** [comment]
You should not open tickets for asking questions about the source code, this issues tracker  is not meant for that. You should rather log in our new chat room: https://gitter.im/red/red using your Github account and ask there. You can also create a new wiki page like a "Source code FAQ", put questions there and ask me on the chat to answer them (so that it can be easily found by newcomers studying the source code).
