### ISSUE TITLE
%lexer.r accepts binary literal, %lexer.red does not

### ISSUE THREAD

**Issue by meijeru** [red/red#1208]
Red programs with a binary literal (e.g. `#{FF}`) compile without protest, even thought the binary! datatype has not yet been implemented. The interpreter protests.

**Comment by dockimbel** [comment]
That feature was introduced a long time ago as I wanted to have a way to both inline native binary code in Red/System programs and specify array of bytes in binary form instead of strings. Though, I have not implemented those features yet, and `binary!` support will be coming soon, so having compiler's lexer already supporting it is fine.
