### ISSUE TITLE
Wish: negate and round should be allowed on vectors of integers and floats

### ISSUE THREAD

**Issue by meijeru** [red/red#1262]
Semantics: application of the actions on an element-by-element basis.

**Comment by PeterWAWood** [comment]
Following the introduction the [Red REP repository for enhancements and wishes](https://gitter.im/red/red?at=5adfeed527c509a7744a3dc8), this issue is being closed.

If you believe that your wish is still valid, please open a new issue for it in the new [red/REP repo](https://github.com/red/REP). It would help if you could include a link to this issue when opening an issue in the REP repository.
