### ISSUE TITLE
Regression on auto-updating display after changing window's pane

### ISSUE THREAD

**Issue by dockimbel** [red/red#1674]
```
view win: layout [
    button "test" [
    	append win/pane make face! [
    		type: 'button
    		text: "new"
    		offset: 70x10
    		size: 40x30
    	]
    	;show win 		<-- shouldn't need show call in auto-sync mode
    ]
]
```

**Comment by dockimbel** [comment]
The following [line](https://github.com/red/red/blob/master/modules/view/VID.red#L342) is causing the problem. 

@qtxie We need to have a look together at how to fix that properly.

**Comment by qtxie** [comment]
@dockimbel As you already know, this [line](https://github.com/red/red/blob/master/modules/view/VID.red#L342) of code is intend to fix the issue in this code in `livecode.red`:
```
if attempt [lay: layout load source/text][
	output/pane: lay/pane
]
```
I just figure out that the problem is when we do `output/pane: lay/pane`, we don't change the owner of the `lay/pane`, the `lay/pane`'s owner is still `lay` object. see the [bind](https://github.com/red/red/blob/master/runtime/ownership.reds#L103) function.

So how do we solve it ? 
1. Do we just change the owner to `output` ?
2. Should we allow multi-owner ?
