### ISSUE TITLE
Script filenames starting with `--` wrongly processed on command-line

### ISSUE THREAD

**Issue by ghost** [red/red#1773]
Creating a file named `--asd.red` with the following content

```
Red []
print 1
```

And then from the Command Prompt -
`red --cli --asd.red` gives output `1`.
But `red --asd.red` produces no output at all in the GUI Console. 

See http://i.imgur.com/TGcg0G8.gifv

**Comment by hiiamboris** [comment]
Looks like this is intentional: https://github.com/red/red/blob/8d712e4ba1b16e1b7a339006d1154aebc9cb7ce4/environment/console/engine.red#L55
Each `--thing` is treated as an option. Should we add a `--` switch that will toggle it off?

**Comment by greggirwin** [comment]
I don't have notes in my old CLI stuff (which is also on my short list of things I think Red would benefit from) about that ever being an issue. @hiiamboris is there any precedent for a toggle switch like that? It seems better to tell people "Don't do that.", because it will make for ugly command lines, which could also be used to hide calls to malicious scripts.

**Comment by greggirwin** [comment]
It's something to keep in mind for a CLI dialect, but this isn't something we'd need to change due a large set of legacy scripts that need it.

**Comment by hiiamboris** [comment]
@greggirwin 
> is there any precedent for a toggle switch like that?

https://unix.stackexchange.com/a/11382

**Comment by greggirwin** [comment]
Now I see what you mean by "toggle", and yes, using `--` to mark the end of options seems like a good idea.

**Comment by greggirwin** [comment]
If it were bash specific, I'd hesitate, but it's a Posix guideline as well.

**Comment by qtxie** [comment]
I think we should check if it's an valid option, if not we take it as a normal argument.

**Comment by hiiamboris** [comment]
@qtxie Wouldn't it be better if we rather complain that the option is invalid? Having `--filenames` is pretty uncommon and if the option is not a valid one then most likely it's a user's typo, or usage of a deprecated option.

**Comment by greggirwin** [comment]
Is there a standard/expected behavior we can follow? My gut says that allowing them to pass through, and be interpreted as operands, is a bad idea. But Postel's Law favors robustness over debuggability. For Red proper this may not be a showstopper, but for our CLI dialect/lib we want to consider it.
