### ISSUE TITLE
WISH: Copy a shown face

### ISSUE THREAD

**Issue by JenniferLee520** [red/red#1852]
I need to copy a face while dealing with its Drag-Start event. I cannot remove the face first, because that would make the face lose the mouse capturing which is not what I want. I would like Red to support copy a shown face.

**Comment by PeterWAWood** [comment]
Following the introduction of the [Red REP repository for enhancements and wishes](https://gitter.im/red/red?at=5adfeed527c509a7744a3dc8), this issue is being closed.

If you believe that your wish is still valid, please open a new issue for it in the new [red/REP repo](https://github.com/red/REP). It would help if you could include a link to this issue when opening an issue in the REP repository.
