### ISSUE TITLE
Maps created with copy inside objects are referenced when object used to create other objects

### ISSUE THREAD

**Issue by Zamlox** [red/red#2039]
```
red>> obj: object [a: copy #()]
== make object! [
    a: #(    )
]
red>> obj1: make obj []
== make object! [
    a: #(    )
]
red>> put obj1/a 'x 1
== 1
red>> obj1
== make object! [
    a: #(
        x: 1
    )
]
red>> obj
== make object! [
    a: #(
        x: 1
    )
]
```
```obj/a``` and ```obj1/a``` references same map even their definition is ```copy #()```

It works ok if map is replaced with block:
```
red>> obj: object [a: copy []]
== make object! [
    a: []
]
red>> obj1: make obj []
== make object! [
    a: []
]
red>> append obj1/a 1
== [1]
red>> obj1
== make object! [
    a: [1]
]
red>> obj
== make object! [
    a: []
]
```

**Comment by dockimbel** [comment]
When you do `obj: object [a: copy []]`, the spec block is evaluated and the object is created. When you then do `obj1: make obj []`, you just create a clone of the prototype object, your `copy []` does not exist anymore.

What happens is part of the creation rules for object: all referenced *series* are copied (and not deep-copied). Map! or object! are not series, so they are shared by default on cloning objects. So, for such datatypes, if you want them to be copied instead of shared, you need to do it manually:
```
obj: object [a: copy #()]
obj1: make obj [a: copy :a]
put obj1/a 'x 1
?? obj1
?? obj
```

**Comment by Zamlox** [comment]
Thanks for explanation.
