### ISSUE TITLE
Using `keep` outside `collect` crashes interpreter.

### ISSUE THREAD

**Issue by rgchris** [red/red#2176]
```
accumulate: take stuff: collect [keep :keep]
accumulate 1
```

Results in:

```
*** Runtime Error 1: access violation
```

**Comment by rgchris** [comment]
(not suggesting using `keep` in such a way *should* work, this is just related to the crash)

**Comment by dockimbel** [comment]
The crash is caused by an attempt to access a local word in `collect` from `keep` while `collect` frame is not on stack anymore. As both functions are compiled, there is currently no safeguards to prevent such crash to happen if `keep` is used outside of `collect`.  Support for functions defined in functions by the compiler is currently limited, so edge cases are likely to cause trouble. This will be improved in the future releases (before 1.0).

For this specific case, `collect` is just a mezzanine for now, it should go native at some point and have specific support from compiler. Also, making `keep` a keyword in collected blocks instead of a function is an option to consider (in such case, the above code would error out on `:keep` access).

**Comment by dockimbel** [comment]
I figured out a way to catch this case and return an appropriate error:
```
red>> accumulate: take stuff: collect [keep :keep]
== func [v /only][either only [append/only collected v] [append collected v] v]
red>> accumulate 1
*** Script Error: collected word is not bound to a context
*** Where: append
```
