### ISSUE TITLE
WISH: parse return keyword.

### ISSUE THREAD

**Issue by ifgem** [red/red#2185]
Behavior: 

```
point: [
    copy left number
    #"x"
    copy right number
    return (reduce ["point" left right])
]
expr: [
    set p1 point 
    ";"
    set p2 point
    return (reduce ["expr" p1 p2])
]

parse "100x100;200x200" expr
["expr" ["point" "100" "100"] [point "100" "100"]]
```

Another example:

```
integer: [
    copy n number
    return (
        to integer! n
    )
]
sub/part "street 100" [set h integer] [h: h + 1] 
"street 101"
```

**Comment by greggirwin** [comment]
R3 added 'return to `parse`, but it broke out of main rule. I've done a number of things in the past to collect data while parsing, and it's a nice idea. You can get close with `collect/keep`, though it's really a collect-as-you-go model (which works if your output is Forth :^), rather than using vars or a stack you can push and pop against (where the return goes). 

I don't know the deeper implications, or what Nenad has in mind for other parse enhancements. e.g. rule-local vars.

We can mock up ideas quickly, and make a list of scenarios.

**Comment by dockimbel** [comment]
@ifgem What is `sub`?

**Comment by dockimbel** [comment]
As there was no further discussion about this request, I'm closing this ticket.
