### ISSUE TITLE
make datatype! <any-value> produces either datatype! or crashes

### ISSUE THREAD

**Issue by meijeru** [red/red#2326]
It should give an error irrespective of the type of the value.

**Comment by meijeru** [comment]
I understand that `make datatype! <integer>` produces the type with the internal number equal to the integer value. Worth documenting?

**Comment by dockimbel** [comment]
It should return an error (as per the MAKE matrix), a datatype! value should not be created by the user that way, only literally. The underlying types numbering should not be exposed as Red level, as such numbers can change, and in the future, have a dynamic assignment (instead of static currently).

Moreover, it's still crashing even with the commit:
```
red>> make datatype! 50

*** Runtime Error 1: access violation
*** at: 00423DFCh
```
