### ISSUE TITLE
make object! from map always gives error, although allowed in the table

### ISSUE THREAD

**Issue by meijeru** [red/red#2339]
```
red>> make object! #(a: 1 b: 2)
*** Syntax Error: invalid construction spec: #(a: 1 b: 2)
*** Where: make
```
Obviously, objects require set-word keys only, so some maps cannot be converted, but the above example should be allowed.

**Comment by dockimbel** [comment]
For now, we will not allow direct conversion between objects and maps (the conversion table will be updated to remove that entry). See #2338. The reason is the different nature of both data structures, one is a namespace aiming at providing local contexts to code, while the other is a dictionary-like structure which can freely grow/shrink using direct path accesses.

**Comment by hiiamboris** [comment]
Carl was there http://www.rebol.net/r3blogs/0142.html
