### ISSUE TITLE
TYPE_ANY_BLOCK and ANY_BLOCK? as defined in macros.reds are missing hash!

### ISSUE THREAD

**Issue by meijeru** [red/red#2340]
TYPE_ANY_LIST *does* include hash!
I don't know if this is on purpose, but in any case, the following gives an error:
```
red>> as hash! [1 2]
*** Script Error: cannot coerce hash! to block!
*** Where: as
```

It is true that one can always do `make/to hash! [1 2]` and even use `to-hash` but for the other members of `any-block!` there is the additional facility of `as`, so why not for `hash!` ?

**Comment by qtxie** [comment]
What I understand is that hash! is a hashtable, we put a layer on it to make it _feel like_ a series.

**Comment by meijeru** [comment]
But in `%environment/scalars.red`, `any-block!` is defined as containing `hash!` so one should include it in order not to confuse. The `#defines` in the `.reds` code should be compatible with the definitions in the `.red` code.

**Comment by dockimbel** [comment]
@qtxie It's the opposite, `hash!` is a block with a hidden hashtable, that's how users should see it. All the API and semantics of hash are identical with the ones of block. 

@meijeru `as hash!` cannot work, because coercion (or type casting) only flips the bits encoding the type, which requires an identical implementation for the types to be compatible. Hash! and block! have different implementations, so can't be transformed that way, they require conversion using `to`.

**Comment by dockimbel** [comment]
I have added TYPE_HASH where due.
