### ISSUE TITLE
Windows prebuilt console version being flagged by Anti-Virus

### ISSUE THREAD

**Issue by soapdog** [red/red#2399]
Just download the prebuilt windows version that is linked on the blog at http://www.red-lang.org/2016/12/incursion-into-explorable-explanations.html. It is being flagged by my antivirus program, this might be happening with other users. I haven't tried running it since I have no idea if this is a false positive. I'd recommend checking the prebuilt versions.

![red-being-flagged](https://cloud.githubusercontent.com/assets/23247/21600671/45311fdc-d124-11e6-8ccc-1f4c37870975.png)

**Comment by endo64** [comment]
It most probably a false positive. See the comments on http://www.red-lang.org/2016/03/060-red-gui-system.html 

> Nenad RakocevicMarch 27, 2016 at 9:58 AM
> Unfortunately, AntiVirus software are sometimes too picky and will inappropriately flag some executables generated by our toolchain. If you have time, please submit a false positive report to Avira, so they can tune their heuristics.
> 
> We usually use virustotal.com to scan our exe and report the false positive, if any, to AV vendors, but this only works for signature-based detection, for checking heuristics, we would need to have *all* the AV software installed and check one by one, which is not doable given our resources.
>

**Comment by geekyi** [comment]
It's a common problem. They might white list it once, but then it would have the problem with another nightly.. send reports when this happens.
To go into more detail about that particular .exe that you are running, it's the UPX compression that triggers it. It says "XPACK.Gen2" Which means a generic compressed executable.
I also used to run Avira since a long time (4+ years?) Recently changed to the default Microsoft antivirus because I couldn't workaround the problem. Let me know if you find a fix

**Comment by retsyo** [comment]
but why "red-23jul16-e730f28.exe" is not been reported as an infected app? 

It is ok for us to mark red in the white list, but how about releasing app for other peoples? Red meets a bad thing like a Chinese programming language (E language, http://www.dywt.com.cn/, which is a VB-like IDE/language) met for years and years, which makes a very negative influence on E language development.

**Comment by geekyi** [comment]
[red windows, jan 5](https://virustotal.com/en/file/882dc67cb3c5d97ebe05920207c03051e2c7fccb48a2e0e7d79f50de47be8f1f/analysis/) 2/55
*NOT* flagged by avira

version @soapdog [downloaded](https://virustotal.com/en/file/5d90e88410730853ed4390d41f8c934282a19d183e0f3a7769edae4dbaa6517e/analysis/) 5/54
This later version seems flagged by avira because the .exe is compressed?

**Comment by retsyo** [comment]
as for `red-05jan17-8e03847.exe`, my `Avira free antivirus` (search engine version 8.03.42.122, virus difination files version 8.12.145.52) on win7 says `TR/Crypt.XPACK.Gen2` is found in `C:\ProgramData\Red\crush-2017-1-5-48687.dll` . 

Red says: 
> Compiling compression library...
> *** Driver Internal Error: Access Error : Cannot open /C/ProgramData/Red/crush-2
> 017-1-5-48687.dll as library
> *** Where: build-compress-lib
> *** Near:  [crush-lib: load/library filename
> crush-compress: make
> ]

In fact I have reported this as https://github.com/red/red/issues/2317, which is actually sovled by no effective sovled method (i.e. add your RED into white list, and don't care other people's PC).

**Comment by dockimbel** [comment]
Avira is unfortunately one of the AV which gives us the most trouble, as it seems to have badly tuned heuristics for detecting unknown threats. 

All our Windows binary are built on a Linux machine under Wine, we never had any single case of positive viral infection, all the reports are false positive, due to poorly-tuned AV software. Don't trust your AV, use [VirusTotal](https://virustotal.com).

**Comment by retsyo** [comment]
Good news. the new released 0.6.2 is not reported by `Avira Connect` as virus! Well done.

But how do you implement this?

**Comment by retsyo** [comment]
ugly! `Avira` says virus again today!

**Comment by michaeldesu** [comment]
Just while I see this - JFY Symantec Endpoint also flags the exe as level [WS.Reputation.1](https://www.symantec.com/security_response/writeup.jsp?docid=2010-051308-1854-99) which seems rather severe since it's purely based data from Symantec’s community of users.

**Comment by retsyo** [comment]
So bad news.

**Comment by dockimbel** [comment]
> Just while I see this - JFY Symantec Endpoint also flags the exe as level WS.Reputation.1 which seems rather severe since it's purely based data from Symantec’s community of users.

On the contrary, this is the weakest categorisation method, as it is not based on the content of the file, but on how many instances of the files are present out there. If you generate an executable from your code, you're the only one to have it, share it with a friend who runs that AV, and it will get flagged because nobody else is using it (the "wisdom of the crowd"...). How silly is that... They are plenty of AV software you can find from VirusTotal list which *never* signaled false positives on Red executables, yet they are big names (Kaspersky for example), they look much more trustable to me, than the one relying on inefficient methods.

**Comment by michaeldesu** [comment]
You're absolutely right - it's what I was suggesting with the term "severe" (i.e. not based on code). I've been using Red nearly every day at work recently for experimenting, and it's been very annoying to see this "reputation" warning - every compile and launch time to be asked 'do I want to quarantine this file' since it's only been known x weeks by less than y users.. and explicitly allow execution. It's been a real test of will. This scheme puts a rather bad taste in the mouth. However recently 0.6.2 did unexpectedly get 'accepted' somehow (I guess it passed some threshold) and I don't see this popup now, until I run the later builds, and it starts all over again. Perhaps once you get near 1.0 you may want to contact Symantec, or hopefully the critical mass is overcome.

**Comment by dockimbel** [comment]
@michaeldesu Thanks for the precision, I misunderstood your sentence.

If you can post some false positive reports to Symantec (we'll do it too), that would be helpful (be sure to explain that the exe is generated by Red language toolchain. The more reports they'll receive, the more chances they'll fix their bogus heuristics.

On the road to 1.0, we'll add code signing to the executables using platform certificates, that should help overcome the few AV who are doing a bad job. For the remaining ones which will keep flagging it wrongly, be sure we'll put the pressure on to make them fix their heuristics as we approach 1.0. ;-)

**Comment by Pomazan-Bogdan** [comment]
https://www.virustotal.com/ru/file/cafdc8ab527d7223769ba1e78c652c865d4239df6d0338f204c362883750f0a2/analysis/1499702018/

**Comment by dockimbel** [comment]
@Pomazan-Bogdan Avira is as bad as usual, I made a new false positive report ten days ago, and they just white-listed the executable I sent, not fixing their heuristics at all...

Qihoo-360 is a Chinese company, known for putting malware/spyware in all their software including their AV...

**Comment by Narvey** [comment]
Avast also flags this as malware.  I don't feel confident using red in Windows because I could have been victim to a MITM attack (how would I know the difference?):

[[https://dl2.pushbulletusercontent.com/h8karOP0tAIC8NbNdUXzicFAGiiWXpw7/2017-10-13%2007.14.31.jpg|alt=Avast moved red to virus chest because Win32:Malware-gen]]

**Comment by geekyi** [comment]
Noting for historical reasons that this was mentioned to Avira: https://twitter.com/red_lang/status/887970289618829312

**Comment by pr-yemibedu** [comment]
Hello,
 So on Windows 10 Pro 64 bit, I installed and launched the GUI console yesterday. I did not think much of it and pinned it to my taskbar to do other things. Today when I went to open it again, the link did not work and Windows Defender reported finding a virus. Same on a re-install. Here is a feedback summary I sent to Microsoft:

```
The Windows Defender Security Center "Learn More" shows No results found for: Trojan:Win32/Critet.BS for the Red Programming language GUI Console exe

No results found for: Trojan:Win32/Critet.BS
The Red programming language has a  GUI console executable that is flagged and removed. It is created from its own installer.

The program quarantined:
 C:\ProgramData\Red\gui-console-2017-8-3-49893.exe
The site for the programming language is here:
 http://www.red-lang.org/
The page for getting the installer is here:
 http://www.red-lang.org/p/download.html
There installer that is used to install the console is here:
 https://static.red-lang.org/dl/win/red-063.exe
The closet the site talks of knowing this is here:
 http://www.red-lang.org/2016/03/060-red-gui-system.html

The Windows Defender Security Center shows the entry in the full history of quarantine. When you click to "Learn More" it goes here:
 https://www.microsoft.com/en-us/wdsi/threats/threat-search?query=trojan:win32/critet.bs&2147726294&page=1&showall=false&sortby=relevance&sortdir=desc&size=10

But the site reports at the bottom "No results found for: Trojan:Win32/Critet.BS"
```

Hopefully that team can respond and whitelist the binaries. Its the only compiler out of 10 that is doing this. I have `Rust, Nim, D, Ada (Gnat), Haskell (GHC), Eiffel, GCC, Ocaml, Go, C#, F#, and VB.Net` installed by the way. Thank you. Good day.

**Comment by greggirwin** [comment]
Thank you for the report @pr-yemibedu ! We're working on this issue. Every report helps, as the AV vendors don't tell us why they give us a false positive. Something that makes us different, aside from being our own compiler, so no emitting the same exact output as common C compilers, is our small size. Maybe if we bloat our app they won't flag it. PowerBASIC had that feature, but for user perception, not AV.

**Comment by pr-yemibedu** [comment]
Hello,
 Maybe you can pack functions differently in the binary or build your own app as a base plus library architecture. The latter would probably help most as it would change the surface area to matching false signatures or heuristics. Plus since it your own tools, you can possible give the user the option in the installer for either `static or modular` that way the default would be static but I can just get on with my day by doing a modular install that would still work. In my everyday work, I don't care about one or two dynamic loads in a GUI application. Thank you. Good day.

**Comment by mohd-akram** [comment]
I compiled a ["hello world" program](https://wesleyhill.co.uk/p/writing-gui-apps-using-the-red-programming-language/) and Windows Defender flagged it as a virus:

````
Program:Win32/Unwaders.C!ml

Alert level: Severe
Status: Quarantined
Date: 8/3/2018

Recommended action: Remove threat now.

Category: Potentially Unwanted Software
Details: This program has potentially unwanted behavior.

Learn more
````

Clicking "Learn more" goes to [this link](https://go.microsoft.com/fwlink/?linkid=142185&name=Program:Win32/Unwaders.C!ml&threatid=242874).

**Comment by greggirwin** [comment]
Thanks @mohd-akram. It's an ongoing battle.

**Comment by amreus** [comment]
Windows Defender is always flagging Red programs compiled with the `-r` option, and sometimes when using the `-c` option.  Sometimes also `C:\ProgramData\Red\console-2017-8-3-49893.exe` is getting quarantined.

[Here ](https://www.virustotal.com/en/file/5bfad0023442cfe0f31f4390fbc39aa9b21e3b53c998cab4e3db010e988b75e5/analysis/)is a VirusTotal submission for a Hello World program compiled using `-c`

[Here ](https://www.virustotal.com/en/file/221d4fc62980e6fa21d7eff5b0ce80a99679576d913749e84dba61e32cf2c9c2/analysis/1535979583/)is a VirusTotal submission for the same Hello World program compiled with `-r`

I also submitted the `-r` helloworld.exe to Microsoft as a false positive. I noticed this cloud/client result:
![image](https://user-images.githubusercontent.com/38442825/44990065-e4307380-af5d-11e8-9ba4-c744637b308c.png)

It gave me the idea to disable the "Cloud delivered protection" option in Defender. This has made the false detections go away so far.  I don't have the knowledge to say if it's better to white-list your Red folder or disable Cloud protection - just pointing out my experience in case it is helpful.

As a side note, sysinternals has a utility called [sigcheck](https://docs.microsoft.com/en-us/sysinternals/downloads/sigcheck) that can submit files to VirusTotal among other things - it's quite convenient.

**Comment by greggirwin** [comment]
Thanks @amreus !

**Comment by lepinekong** [comment]
Got Trojan:Win32/Fuerboos.C!cl: it is very annoying false negative or not, I have only messages with red and none with other exes. So I don't feel confident to tell other people to even try red.

**Comment by lepinekong** [comment]
If it is due to compression, is it really needed to compress it ?

**Comment by endo64** [comment]
@lepinekong See the notes here for AV issues: https://github.com/red/red/wiki/%5BNOTE%5D-Anti-virus-false-positives

**Comment by camelite** [comment]
Windows defender reports C:\ProgramData\Red\gui-console-2018-11-22-8164.exe from current pre-built binary red-064.exe as malware Unwaders.A!ml

**Comment by Jose-Moreno** [comment]
Just wanted to report that Windows Defender latest update database from September 22nd 2020 has flagged **console-2018-11-22-8164.exe** (`red --cli`) as **Trojan:Win32/Wacatac.B!ml** 

I'm new to Red but I really doubt that after 3 months of the file sitting in my HDD, it just magically became a trojan 🙄. Anyway already whitelisted the red folders and i'll follow the recommendations guide posted by endo64. Thanks.

**Comment by plegoff** [comment]
Hello, I have downloaded the latest release of Red-View (red-view-30sep22-a2fe8a526.exe) on my PC Windows 10 Enterprise 20H2. My anti-virus (McAfee EndPoint Security 10.7.0.3437, with Real Protect Cloud) removes the executable as soon as it is executed. Is there a solution to use red on Windows? The release is flagged by McAfee as : Real Protect-PENG4!5EE12CB32250 Trojan. 
![McAfee-Red](https://user-images.githubusercontent.com/259559/193275048-5af9062a-86b9-4697-9b62-0af09724a745.png)

**Comment by greggirwin** [comment]
Does McAfee have no mechanism to flag a file as safe?

**Comment by plegoff** [comment]
McAfee has a mechanism to flag a file as safe, but in my issue, I can't use this mechanism : this issue occurs on my company PC and some administrator rights are restricted by rules I cannot change.
