### ISSUE TITLE
Compiling code in debug mode (`-d`) does not work unless release mode (`-r`) is used 

### ISSUE THREAD

**Issue by ghost** [red/red#2463]
Debug mode (`-d`) only works in release mode.

When using libred, it produces a normal executable without any debugging code.

Either this is an intended side-effect of libredRT and needs to be documented at the time of 0.6.2 release
*or*  
This is a an unintended side-effect of libredRT (bug) and needs to be fixed.

**Comment by dockimbel** [comment]
The debug mode works fine without having to use release mode (regardless how libRedRT is compiled):
```
Red [file: %debug.red]

#system [
    probe #either debug? = yes ["debug mode"]["normal mode"]
]

> red -c -d debug.red
> debug
debug mode
```

If you need a debugging version of libRedRT, then you need to refresh it with `-d` mode:
```
> red clear
> red -c -d debug.red
```

**Comment by nc-x** [comment]
Okay, it is due to `release libRedRT` and `debug libRedRT` -
  
I took a piece of code from one of the open issues on github and -
` red -c -d test.red` gives only
```
*** Runtime Error 1: access violation
*** at: 100853A7h
```
whereas 
```
red clear
red -c -d test.red
```
gives the expected stack trace.
  
**Only the second output is expected and not the first one. This is gonna be plain confusing.**
  
As I have commented over here https://github.com/red/red/issues/2371, I would prefer to have the `libRedRT-<some_hash>.dll` file in the standard folder. And along with that, I would now prefer to have another `libRedRT-debug-<some_hash>.dll` file present in that folder. Then the compiler should link to the `libRedRT-debug-<some_hash>.dll` when `-d` is passed. And only when R/S code is present in the program, the libRedRT.dll and/or libRedRT-debug.dll should be rebuilt, locally in the folder of the project.

**Comment by dockimbel** [comment]
> I took a piece of code from one of the open issues on github and -

But you didn't say which one, so we cannot reproduce, nor say much about your results...

> red -c -d test.red gives only
> red -c -d test.red

You've compiled twice with the same options or is it a typo? Anyway, we can't reproduce as you didn't provide the source code you've used.

> Because, I don't really see any advantage to That gives you 4 possible combinations depending on what/how you want to debug.

The advantage is that you choose how you want to handle it. If you are modifying the Red runtime code and want to debug it, you can compile a debug version of libRedRT and keep using only that one. If you are only interested in debugging your own code, then you just compile a normal version of libRedRT and you can then compile your own code in normal or debug mode, both would work fine. In short, the way libRedRT is compiled is not related to the way your own code is compiled. So you decide the compilation mode for libRedRT and your own code separately (hence the 4 possible combinations).
