### ISSUE TITLE
WISH: DIR should accept file! argument that is not a folder/directory

### ISSUE THREAD

**Issue by meijeru** [red/red#2476]
Currently, DIR or likewise LS, accepts an argument of type `file!` but only acts on it if that argument represents a directory/folder. In connection with the use of wildcards, it would be nice if a file argument that does not end in a `/` would also be accepted. Example:
```
red>> dir *.bat
*** Access Error: cannot open: %/C/Projects/Red/programs/*.bat/
*** Where: read
```
 The function adds the `/` itself...

**Comment by dockimbel** [comment]
`dir` and `ls` commands purpose in Red console is only for listing directory's content, that is why they expect a directory name as argument.

**Comment by PeterWAWood** [comment]
Following the introduction of the [Red REP repository for enhancements and wishes](https://gitter.im/red/red?at=5adfeed527c509a7744a3dc8), this issue is being closed.

If you believe that your wish is still valid, please open a new issue for it in the new [red/REP repo](https://github.com/red/REP). It would help if you could include a link to this issue when opening an issue in the REP repository.
