### ISSUE TITLE
BODY-OF is not defined for vector! values

### ISSUE THREAD

**Issue by meijeru** [red/red#2507]
The newest conversion matrices mention BODY-OF vector! as a source for `make/to` with target `any-list!`.
Even though the conversion works,it obviously does not go via `body-of`
```
>> v: make vector! [1 2 3]
>> body-of v
*** Script Error: reflect does not allow vector! for its value argument
>> to block! v
== [1 2 3]  ; OK
```

**Comment by endo64** [comment]
Related to #1957

**Comment by dockimbel** [comment]
@meijeru The notes in the conversion matrix are just describing the kind of conversion that happens using existing semantics from the language, it does not mean that such conversion methods needs to be actually supported. I could have used `to-block` in order to describe the conversion in the matrix for such case, but I considered that `body-of` was shorter and more generic.
