### ISSUE TITLE
More consistent *-of naming

### ISSUE THREAD

**Issue by Kaj-de-Vos** [red/red#255]
I looked through the REBOL dictionary for functions that are misnamed according to the new *-of convention. These certainly qualify:

```
head
tail
first ... tenth
last
```

These words are nouns that fail to communicate an action on an argument. Often you would want to use them as variable names instead.

How would you feel about using the *-of forms instead? We would move a little farther away from REBOL, but it would really be clearer, especially in complex expressions and for beginners. Simple assignments could still be used to reestablish compatibility with REBOL code.

**Comment by greggirwin** [comment]
Current list of funcs that end in `?` but don't return a logic value (not counting `?` and `??`). The vast majority of funcs ending in `?` _do_ return a logic value.
```
context?
distance?
index?
length?
metrics?
offset?
react?
sign?
size?
type?
```
If we really want to follow the verb rule, we should name things `get-*`, rather than `*-of`. 

Consistency is good, but I don't think we can apply a hard and fast rule, universally, forever. All we can provide is guidelines and rationale when it comes to naming. To that end, a trailing `?` sigil can simply mean: I'm asking a question. "What is X?" Sometimes the answer is Yes/No, in which case, the question is framed as "Is this [a/an] X?" or "Is this expression true?"

Does that mean `?` could be used almost anywhere, because half the time we're asking about things? Yes it does. Just removing the sigil from the above funcs would cause naming conflicts, and perhaps some confusion (at least for old timers). But I don't think this is a problem, per se. At least not one with a solution that's better, only different. It's something you learn, you learn quickly, and then seems very natural. It's simply part of the vocabulary to learn, and you have hints to help you.

I vote that we close this ticket, and if someone wants to propose renaming any of the above funcs, with concrete reasons for each, use new tickets.

**Comment by dockimbel** [comment]
After reading again this thread, I still stand by my early [comment](https://github.com/red/red/issues/255#issuecomment-8780507) about it. So, for now, we close this debate.
