### ISSUE TITLE
WISH: index?  could be allowed on any-word!

### ISSUE THREAD

**Issue by meijeru** [red/red#2618]
`index?` is currently allowed on `word!` values and yields the index in the context. There is no reason
why it should not be allowed on `lit-word! get-word! set-word! refinement!` and `issue!` values.

**Comment by PeterWAWood** [comment]
Following the introduction of the [Red REP repository for enhancements and wishes](https://gitter.im/red/red?at=5adfeed527c509a7744a3dc8), this issue is being closed.

If you believe that your wish is still valid, please open a new issue for it in the new [red/REP repo](https://github.com/red/REP). It would help if you could include a link to this issue when opening an issue in the REP repository.
