### ISSUE TITLE
function with lit-word as formal argument behaves differently from Rebol

### ISSUE THREAD

**Issue by meijeru** [red/red#2622]
A lit-word formal argument induces non-evaluation of the actual argument, and should therefore also prevent the evaluation of the infix operator expression. Rebol does this, but Red gives an error.

Rebol:
```
>> f: func ['a][2 * a]
>> probe :f
func ['a][2 * a]
>> f 1
== 2
>> f 1 + 2
== 4   ;; not 6!
```
Red:
```
>> f: func['a][2 * a]
== func ['a][2 * a]
>> f 1
== 2
>> f 1 + 2
*** Script Error: + operator is missing an argument
*** Where: catch
```

**Comment by meijeru** [comment]
Related: `quote +` does not work, i.e. operators do not behave like other words. E.g. `quote !` is `!`.

**Comment by dockimbel** [comment]
Related to #1850.

**Comment by greggirwin** [comment]
Between Rebol and Red, which behavior is better? Breaking the rule of op! precedence, or stopping you rather than giving you an unexpected result? I vote for the latter.

My view, and let's document this somewhere, is that it's a current limitation. Lit args are...necessary but not easy. They have specific purposes and benefits (big ones), but may be confusing. There's an easy, if imperfect solution: Fix it with language. Tell people that if they're going to use lit args, there are guidelines <create document for this>, and one of them is to always include a type check for the arg. e.g.
```
>> f: func ['w [word!]][2  * w]
== func ['w [word!]][2 * w]
>> f 1 + 2
*** Script Error: f does not allow integer! for its 'w argument
*** Where: f
*** Stack: f
```
How does that sound?

**Comment by 9214** [comment]
> Related: `quote +` does not work, i.e. operators do not behave like other words. E.g. `quote !` is `!`.

This has been fixed (see https://github.com/red/red/issues/3840).

**Comment by meijeru** [comment]
I refer to the conversation in Gitter red/help chat, and close this issue.

**Comment by 9214** [comment]
For the reference, said conversation starts somewhere [here](https://gitter.im/red/help?at=5d8e1f5a66c8b4512228a09d).
