### ISSUE TITLE
Inconsistency in integer! <-> logic!  conversion with TO 

### ISSUE THREAD

**Issue by meijeru** [red/red#2645]
```
>> to integer! true
*** Script Error: cannot MAKE/TO integer! from: true
*** Where: to
>> to integer! false
*** Script Error: cannot MAKE/TO integer! from: false
*** Where: to
>> to logic! 1
== true
>> to logic! 0
== true
```
See also #2644. I do not think that this conforms to the principle of least surprise 😈

**Comment by greggirwin** [comment]
%integer.reds has special handling for `make` with a `logic!` val. `To` does not. It's possible that it's due to `make` being done, and `to` work coming later but not moving that piece. There are helpers for a couple other types, so a `from-logic!` may also make sense. If that works for Team Red, I can look at making the change.

**Comment by dockimbel** [comment]
There is a reason why we have `to` and `make` and not a single action instead. The rules for *conversion* and the rules for *construction* can differ. And that is not an inconsistency, it is a on-purpose design choice, separating rules into these two category, in order to offer more features while keeping them meaningful to users.

We don't have any principle of least surprise to abide by, as Rebol and Red live in their own abstraction layer, there isn't any mainstream language which comes close to them. What matters is only internal consistencies, not consistency with languages living at an opposite side of the abstraction scale.

All values are `true` except `false` and `none`. From this, it means that:
```
>> to logic! 1
== true
>> to logic! 0
== true
```
is the expected result. In consequence, `true` (and by extension `false`), cannot be mapped back to an integer value, so we block _conversion_ to integer!, returning an error.

But for the sake of boolean logic support, we also provide a mechanism to _construct_ `true` and `false` values from 1 and 0, through `make`, so `make integer! <logic>` is allowed.

For the sake of consistency and reducing confution, we could to block `make` too, though, that would remove a feature and introduce an arbitrary incompatibility with Rebol3. Your opinions and better suggestions on that topic are welcome.

**Comment by dockimbel** [comment]
@9214 Currently:
```
list: [a 3 b 9 c 4 d 0 e 8]
>> foreach w [a d] [if to-logic select list w [print "found!"]]
found!
found!
>> foreach w [a d] [if select list w [print "found!"]]
found!
found!
```
With your proposition, we would get:
```
>> foreach w [a d] [if to-logic select list w [print "found!"]]
found!
>> foreach w [a d] [if select list w [print "found!"]]
found!
found!
```
So, quite a big inconsistency, `0` value could mean `true` or `false` depending how you use it...

**Comment by 9214** [comment]
@dockimbel I think you misunderstood - *my* proposal is to leave `to` as is (see last paragraph). I'll try to rephrase better:
- @meijeru proposal should be accepted **if Red team wants** to keep **compatibility** with Rebol2 as better as possible.
- @meijeru proposal should be declined **if Red team wants** to keep Red semantics **consistent** with "everything is true except `false` or `none`" rule.
- @9214 thinks that @meijeru proposal should be declined and current `to` behavior should stay untouched, because it's **consistent** with Red semantics and we have `make ...` alternatives which are **compatible** with Rebol2.

**Comment by dockimbel** [comment]
@9214 Sorry, misread it, will rephrase my comment.

**Comment by 9214** [comment]
@dockimbel no worries, I'll edit my first message so you could delete your apology and I'll in turn delete this message 😉

**Comment by greggirwin** [comment]
Started https://github.com/red/red/wiki/%60to%60-vs-%60make%60

**Comment by dockimbel** [comment]
The goal of Red is not to be `*xx% compatible with R2*, that is rather the result of the design decisions that are been made, where often the R2 human-friendlier semantics better match Red goals than R3's one. Though, in cases like this one, the design choice of R2 has proven to be more of a burden for users than a help. This was fixed in R3, and Red adopted the same solution.
