### ISSUE TITLE
Inconsistency in comparing object with error

### ISSUE THREAD

**Issue by meijeru** [red/red#2657]
```
>> e: try [1 / 0]
*** Math Error: attempt to divide by zero
*** Where: /
>> o: context?  in e 'id
== make object! [
    code: none
    type: 'math
    id: 'zero-divide
    arg1: ...
>> e = o
== true
>> o = e
== false
```

**Comment by meijeru** [comment]
The `false` result is the correct one. BTW in the above example also `e == o` yields `true` which it shouldn't.

**Comment by endo64** [comment]
@meijeru Why `false` is the correct one?

**Comment by meijeru** [comment]
I thought so at the time. Meanwhile I am convinced that `=` should give true in both directions, and that `==` should give false (`==`  requires equality of types).

**Comment by hiiamboris** [comment]
It's crazier even:
```
>> o = e
== false
>> e = o
== true
>> e == o
== true
>> o == e
== false

>> f: e
>> f = e
== false
>> e = f
== false
>> e == f
== false
>> f == e
== false
```

**Comment by dockimbel** [comment]
It will now return `false` for the `o = e` and `o == e`, so no loose comparison allowed. Supporting a loose mode would require significantly more code for all the combinations, as it needs to include other object-like types (like `port!`  and maybe others to come). Moreover, the nature of `object!` might change before 1.0, so that it will affect other object-like types and how they relate to each-others.
