### ISSUE TITLE
suffix? allows an email! argument, which makes no sense

### ISSUE THREAD

**Issue by meijeru** [red/red#2688]

**Comment by dockimbel** [comment]
Makes sense to me:
```
>> suffix? name@domain.com
== %.com
```

**Comment by greggirwin** [comment]
The hostname/domain part is dot separated segments, though normally there is just the base name and the TLD. Currently, email! values can have more information after the hostname, which is nice, because they could hold valid XMPP/Jabber IDs and are somewhat extensible. In that case, `suffix?` works the same as it does with files. I think it's worth keeping, but having an example use-case would be nice as well.
