### ISSUE TITLE
WISH: sqrt, log-e, log-2, log10 should test on positive argument

### ISSUE THREAD

**Issue by meijeru** [red/red#2701]
Both R2 and R3 do this. Red gives NaN as result.

**Comment by dockimbel** [comment]
Red is following IEEE-754 standard by default, which specifies that NaN is the expected result in such cases. Though, IEEE-754 is not always suitable for Red users, so we plan to add a Rebol-compatible mode, where errors will be returned in such case. In order to do so, we need a way to alter such mode locally only, and we haven't defined such way yet.

**Comment by meijeru** [comment]
Thanks. May I suggest "deferred"status?

**Comment by PeterWAWood** [comment]
Following the introduction of the [Red REP repository for enhancements and wishes](https://gitter.im/red/red?at=5adfeed527c509a7744a3dc8), this issue is being closed.

If you believe that your wish is still valid, please open a new issue for it in the new [red/REP repo](https://github.com/red/REP). It would help if you could include a link to this issue when opening an issue in the REP repository.
