### ISSUE TITLE
[Shape] Wish: Get the shape (glyph) of text in certain font

### ISSUE THREAD

**Issue by JenniferLee520** [red/red#2750]
I wish I could get the outline shapes (glyphs) of text strings in certain font, so I could use them as clip-regions or manipulate them somehow.

**Comment by PeterWAWood** [comment]
Following the introduction of the [Red REP repository for enhancements and wishes](https://gitter.im/red/red?at=5adfeed527c509a7744a3dc8), this issue is being closed.

If you believe that your wish is still valid, please open a new issue for it in the new [red/REP repo](https://github.com/red/REP). It would help if you could include a link to this issue when opening an issue in the REP repository.
