### ISSUE TITLE
WISH: KEEP ONLY support in PARSE

### ISSUE THREAD

**Issue by rebolek** [red/red#2899]
See this code:

```
>> parse "ab" [collect [set v1 "a" set v2 "b" keep (reduce [v1 v2])]]
== [[#"a" #"b"]]
```

This is actually `keep/only` equivalent, not `keep`.

Expected behaviour:
```
>> parse "ab" [collect [set v1 "a" set v2 "b" keep only (reduce [v1 v2])]]
== [[#"a" #"b"]]
>> parse "ab" [collect [set v1 "a" set v2 "b" keep (reduce [v1 v2])]]
== [#"a" #"b"]
```

**Comment by PeterWAWood** [comment]
Following the introduction of the [Red REP repository for enhancements and wishes](https://gitter.im/red/red?at=5adfeed527c509a7744a3dc8), this issue is being closed.

If you believe that your wish is still valid, please open a new issue for it in the new [red/REP repo](https://github.com/red/REP). It would help if you could include a link to this issue when opening an issue in the REP repository.
