### ISSUE TITLE
make url! [mailto abc@def.com] produces invalid url

### ISSUE THREAD

**Issue by meijeru** [red/red#2902]
```
>> make url! [mailto abc@def.com]
== mailto://abc@def.com
```
should be
```
== mailto:abc@def.com
```

**Comment by dockimbel** [comment]
The current result is consistent with other scheme names. We will not make [special lists](https://tools.ietf.org/html/rfc3986#section-1.1.2) for changing the MOLDed `url!` formatting output. It is up to the user to format the URL differently. The future `format` dialect could also provide some help there (@greggirwin).

**Comment by DideC** [comment]
`replace form mailto://abc@def.com "//" ""`
Not so hard !

**Comment by meijeru** [comment]
So the current facility is a partial one. Should be documented as such.

**Comment by greggirwin** [comment]
I don't think it's partial so much as consistent.

**Comment by meijeru** [comment]
It is not consistent, just simplistic, because it adds `://` after the protocol regardless of its nature.

**Comment by greggirwin** [comment]
How is that not consistent? I agree that it creates a non-conformant mailto url, and would also for a number of others. The alternative is to head down the path outlined in https://tools.ietf.org/html/rfc3986#section-3.1 and implement special rules for *every* scheme, which means a catalog area in the system for new schemes as well, because users may create their own, yes?

This is a case where I think someone would have to make a strong argument *and* provide an acceptable solution, for the change to be considered. 

It's easy to document the current behavior, and also easy to work around.

**Comment by greggirwin** [comment]
Step one might be to write a mezzanine that does this. Not hard to do, and provides a concrete basis for discussion.

**Comment by dockimbel** [comment]
> It is not consistent, just simplistic, because it adds :// after the protocol regardless of its nature.

The `url!` datatype makes no differences between different schemes, they are all treated equally, that is consistency.

For the different formatting, that should be handled at high-level than the datatype, using mezzanine code.
