### ISSUE TITLE
WHILE keyword in PARSE stops looping at the tail of the input series.

### ISSUE THREAD

**Issue by rgchris** [red/red#2907]
The [definition]() of WHILE states: *"repeat rule zero or more times until failure regardless of input advancing."* However WHILE also stops repeating when the input series reaches the tail even though the rule, if tested, would not fail.

```rebol
parse "" [while []]
        ; would result in infinite loop

parse "" [while [end ()]]
        ; would result in infinite loop

parse "aaa" [while ["a" | end (probe 'end) fail]]
        ; would process if the sequence of A's ended at the tail
```

*('end is not probed)*

It is difficult to reproduce this behaviour otherwise.

**Comment by dockimbel** [comment]
@rgchris Your "definition" link is wrong.

**Comment by rgchris** [comment]
D'oh! A loop in and of itself :)

Defined [here](http://www.red-lang.org/2013/11/041-introducing-parse.html)...

**Comment by rgchris** [comment]
I wrote [this example](https://gist.github.com/rgchris/67cd497c097d7ff768a15424057bbdea) as a reduced version of something I'm working on that breaks.

**Comment by dockimbel** [comment]
I have implemented your proposition in a local Red branch to experiment with it. After such change, basically, you need to have a failed rule, or use an explicit `break` of `fail` in order to exit the `while` loop.  So, it is very easy then to run into an infinite loop.

Do you have any example in Rebol3, where you can exit from a `while` loop in a different way?

**Comment by dockimbel** [comment]
I have decided to implement your proposal for two reasons:
* Make `while` more useful by making its semantics more different than `any`.
* Be compatible with `while` implementation in R3 and old `any` semantics in R2.
