### ISSUE TITLE
Parse error then trying to build a macro from function defined in other file

### ISSUE THREAD

**Issue by 9214** [red/red#2931]
```Red
Red [File: %my-code.red]

#macro my-macro: func [][do %my-func.red]
probe [my-macro]
```
```Red
Red [File: %my-func.red]

func [][42]
```
This mumbo-jumbo results in
```
*** Script Error: PARSE - get-word refers to a different series! :s
*** Where: parse
*** Stack: expand-directives expand
```

**Comment by dockimbel** [comment]
That code does not compile here, as macros in compiler are run by Rebol and not Red, so the `do` fails as it takes a Red file instead of a Rebol one.

**Comment by dockimbel** [comment]
The bug is fixed, but there is also an issue with your code (beyond the compiler vs interpreter difference). You are using `do` which results in creating a `function!` value that your macro is inserting in the source code. While the interpreter can handle such value, the compiler will never be able to handle that, as a `function!` value is a run-time construction.
