### ISSUE TITLE
Wish: Press the ESC key to break a running loop on console

### ISSUE THREAD

**Issue by Blocode** [red/red#2987]
So I can
```Red
>> forever [print now/time wait 1]
12:22:46
12:22:47
12:22:48
(escape)
>>
```

**Comment by PeterWAWood** [comment]
Following the introduction of the [Red REP repository for enhancements and wishes](https://gitter.im/red/red?at=5adfeed527c509a7744a3dc8), this issue is being closed.

If you believe that your wish is still valid, please open a new issue for it in the new [red/REP repo](https://github.com/red/REP). It would help if you could include a link to this issue when opening an issue in the REP repository.
