### ISSUE TITLE
new-line markers inside block are set for no reason

### ISSUE THREAD

**Issue by 9214** [red/red#2992]
Following snippet:
```Red
probe collect [
    foreach [l d] "a1b2" [
        keep reduce [
            (to integer! l) - 1
            to integer! form d
        ]
    ]
]
```
As expected, results in:
```Red
[96 1 97 2]
```
But if I rewrite `(to integer! l) - 1` to `-1 + to integer! l`, it will yield the same result, but formatted differently, as if new-line markers are setted.
```Red
probe collect [
    foreach [l d] "a1b2" [
        keep reduce [
            -1 + to integer! l
            to integer! form d
        ]
    ]
]
```
```Red
[
    96 1
    97 2
]
```
Looks like in this case `keep` (or `reduce`?) somehow preserves the content exactly, because if I rewrite snippet to:
```Red
probe collect [
    foreach [l d] "a1b2" [
        keep reduce [-1 + to integer! l to integer! form d]
    ]
]
```
It again will be
```Red
[96 1 97 2]
```

**Comment by dockimbel** [comment]
New-line markers are set everywhere as soon as you format your source code into multiple lines. So:
```
reduce [
    -1 + to integer! l
```
sets a marker just after the opening bracket. Markers are held in value slots, so `-1` value is holding that marker, which remains there after `reduce` is evaluated, because the first value is left unchanged by the reduction, just been copied in the newly created block.

But in:
```
reduce [
    (to integer! l) - 1
```
The marker is held in the `(to integer! l)` value slot, but that value is replaced by a new one, so the marker is reset. The marker could be preserved by the `reduce`, though, I am not sure if all could be preserved in all cases, like in this one:
```
reduce [
    (to integer! "5")
    -
    1 2
]
```
At best, we could get:
```
[
    4 2
]
```
I'm not sure it's worth the trouble, as you can set those markers anyway the way you want using `new-line` function.

The current Red behavior is the same as in Rebol.

**Comment by dockimbel** [comment]
I think the value slot headers are not cleared from the new-line marker flags, so the flag is propagating.
