### ISSUE TITLE
Wish: Select or Pick a portion from time and date.

### ISSUE THREAD

**Issue by Blocode** [red/red#3013]
In Rebol 3, I can do the following code.
```Red
n: now
pick n 'time
pick n 'date
```

**Comment by meijeru** [comment]
the components of a `time!` or  `date!` value have the following numbers:
for `time!` values: `1 ~ hour 2 ~ minute 3 ~ second`
for `date!` values: `1 ~ date 2 ~ year 3 ~ month 4 ~ day 5 ~ zone 6 ~ time 7 ~ hour 8 ~ minute 9 ~ second 10 ~ weekday 11 ~ yearday = julian 12 ~ timezone 13 ~ week 14 ~ isoweek`

that should be enough

**Comment by meijeru** [comment]
BTW, these numbers can be found from `system/catalog/accessors`

**Comment by dockimbel** [comment]
@meijeru For compatibility with Rebol only.

**Comment by PeterWAWood** [comment]
Following the introduction of the [Red REP repository for enhancements and wishes](https://gitter.im/red/red?at=5adfeed527c509a7744a3dc8), this issue is being closed.

If you believe that your wish is still valid, please open a new issue for it in the new [red/REP repo](https://github.com/red/REP). It would help if you could include a link to this issue when opening an issue in the REP repository.
