### ISSUE TITLE
WISH: control over compiler warnings

### ISSUE THREAD

**Issue by Oldes** [red/red#3047]
Would it be possible to add some control over warnings, which are displayed. Actually I would like to hide warnings like:
```
*** Warning: type casting from pointer! to pointer! is not necessary 
```
because it would simplify use of Red/System macros.

**Comment by PeterWAWood** [comment]
Following the introduction of the [Red REP repository for enhancements and wishes](https://gitter.im/red/red?at=5adfeed527c509a7744a3dc8), this issue is being closed.

If you believe that your wish is still valid, please open a new issue for it in the new [red/REP repo](https://github.com/red/REP). It would help if you could include a link to this issue when opening an issue in the REP repository.
