### ISSUE TITLE
WISH: CATCH/THROW in Parse

### ISSUE THREAD

**Issue by rgchris** [red/red#3056]
Goal: to allow a sub-rule to return a value to the calling rule.

Example:

    ctx-escape: make object! [
        escapes: #(newline: "^/" tab: "^-" foo: "foo")
        rule: [
            #"\" [
                  "n" throw (escapes/newline)
                | "t" throw (escapes/tab)
                | "f" throw (escapes/foo)
            ]
        ]
    ]

    ctx-text: make object! [
        escape: get in ctx-escape 'rule
        chars: complement charset "\"
        rule: [
            any [
                  copy text some chars (probe text)
                | set token catch escape (probe token)
            ]
        ]
    ]

    parse "abc\fdef" ctx-text/rule

In this instance, you have a context dedicated to escape sequences and can return the value associated with a matched sequence without requiring a word external to the two contexts or by copying a portion of the source. There is a little crossover in utility with COLLECT/KEEP, however CATCH/THROW offers a little more versatility.

**Comment by PeterWAWood** [comment]
Following the introduction of the [Red REP repository for enhancements and wishes](https://gitter.im/red/red?at=5adfeed527c509a7744a3dc8), this issue is being closed.

If you believe that your wish is still valid, please open a new issue for it in the new [red/REP repo](https://github.com/red/REP). It would help if you could include a link to this issue when opening an issue in the REP repository.
