### ISSUE TITLE
SPLIT does not mimic R2 behaviour with STRING! delimiter

### ISSUE THREAD

**Issue by rebolek** [red/red#3095]
### Expected behavior

This is R2 version of `parse`:

```
>> line: "a,s.d#f;g"
== "a,s.d#f;g"
>> parse line ",.#;"
== ["a" "s" "d" "f" "g"]
```

### Actual behavior

However, Red's `split` can’t reproduce the behaviour:

```
>> line: "a,s.d#f;g"
== "a,s.d#f;g"
>> split line ",.#;"
== ["a,s.d#f;g"]
```

### Steps to reproduce the problem

See above 👆.

### Red version and build date, operating system with version.

latest version on macOS

**Comment by xqlab** [comment]
It can
```
>> line: "a,s.d#f;g"
== "a,s.d#f;g"
>> split line to-bitset ",.#;"
== ["a" "s" "d" "f" "g"]
>>
```

**Comment by rebolek** [comment]
Right, it can, but the question is, if it's bug or feature. I can live with both I guess 😃

**Comment by xqlab** [comment]
feature by design

**Comment by dockimbel** [comment]
It's by design.

Red's `split` is not meant to be limited to what R2's splitting with Parse could accomplish. Splitting with a sequence of characters instead of just a set of characters is an example of such extended feature. For splitting with a set of characters (like R2's parse), you have to provide a `bitset!` as shown above.
