### ISSUE TITLE
WISH Gauge widget

### ISSUE THREAD

**Issue by planetsizecpu** [red/red#3110]
As we commented at the forum, it will be useful a clock-like analog gauge widget for measurements, it may register numerical values, from a given range negative/positive, for a variety of uses, such for example, sound volume meters, bandwidth, etc. So it may accept as parameters the range values, and a text string for display inside the scale, such as "Db" or "Mbps". About scale, it may display some marks to help user.

**Comment by dockimbel** [comment]
We only provide native widgets for now. Does such widget exist in the major 3 OS API (Win/Mac/Lin)?

**Comment by planetsizecpu** [comment]
I just saw an app at mechanical workshop last year, IIRC there was an old ruggered computer in top of a cart, I believe running WinXP, just at the moment I wondered to have these widgets on Red, it was just a momentary thought.

**Comment by planetsizecpu** [comment]
Thinking deep, it may have similar functionality as `progress` widget, only having in mind that different aspect in its simplest form. Also there is the scale range and accepted values range (may be negative), if we want to build it a more complete way. Just my thougths. It would be a nice pratice for me, but I does not feel myself skills enough at this moment :), I guess this widgets type shoud be done in R/S

**Comment by PeterWAWood** [comment]
Following the introduction of the [Red REP repository for enhancements and wishes](https://gitter.im/red/red?at=5adfeed527c509a7744a3dc8), this issue is being closed.

If you believe that your wish is still valid, please open a new issue for it in the new [red/REP repo](https://github.com/red/REP). It would help if you could include a link to this issue when opening an issue in the REP repository.
