### ISSUE TITLE
WISH: index? none returns none

### ISSUE THREAD

**Issue by meijeru** [red/red#3144]
### Expected behavior

`index? find "abcd" "ef"` -> `none`

### Actual behavior

`index? find "abcd" "ef"` -> *error message*

This extension of `index?` would be helpful for shortening lookups that are meant to yield an index or e.g. 0 if not found. We would be able to write:

`any [index? find "abcd" "ef" 0]`

Currently this has to be written as:

`either f: find "abcd" "ef" [index? f][0]`

which consumes an intermediate variable and is a bit more verbose.
There are precedents for built-in functions on series which yield `none` for `none`.

**Comment by greggirwin** [comment]
See also: https://github.com/red/red/issues/2618

**Comment by dockimbel** [comment]
`0` is an invalid position in series (should yield an error in the future when trying to access it). So, it means you would test for a zero index value later in the code... in such case why not just rely on `find` returning `none` for this special case?

> There are precedents for built-in functions on series which yield none for none.

Yes, but the less of them we have, the better, as they lower the robustness of user code, by making some error cases passing silently. The goal of such none-transparency is to be able to chain calls and do nothing in case of `none`, avoiding an extra `either` construct. In the above case, it still requires an extra conditional construct (`any`), so that is not the same use-case as for other none-transparent functions.

**Comment by meijeru** [comment]
In view of the discussion on Gitter I close the issue.

**Comment by greggirwin** [comment]
Added note by Doc in gitter chat: 

> ...a frequent usage of index? can usually be a code smell for non-idiomatic Redbol code. Series with their implicit index, can cover most needs already without having to extract and directly manipulate index values. That is something many/most Redbol newcomers are missing.
