### ISSUE TITLE
bit shift not allowed on binary datatype

### ISSUE THREAD

**Issue by pijoter** [red/red#3163]
### Actual behavior
>> shift #{55} 2
*** Script Error: shift does not allow binary! for its data argument
*** Where: shift
*** Stack:  
### Red version and build date, operating system with version.
>> about
Red for Windows version 0.6.3 built 25-Nov-2017/16:24:59+01:00

**Comment by dockimbel** [comment]
The semantics of `shift` do not play well with series, which have a dynamic size. Such bitshifting operations would be costly on a series. Do you have some use-cases?

If your need is only for 32-bit values, you should rather use integers (they accept an hexadecimal form as input):
```
shift 55h 2
== 21
to-hex shift 55h 2
== #00000015
```

**Comment by greggirwin** [comment]
I have old `shift` and `rotate` mezzanines from R2 (pre-shift availability), that support series. There are a few times I've used them, but not a lot. They *can* be useful when you want to treat a series as a fixed size data structure. `Rotate` is easy because you already have value slots filled. `Shift` is only a little tricky, and mine, IIRC, used a `make-empy-value` sub-func, so blocks would get `none`, binary `0`, and strings `null` inserted in slots that "shifted out". You can also override the empty value. 

That doesn't address this exact ticket, or @pijoter's need, if he needs bit shifting in a binary, which would be at odds with shifting byte values in a binary series.

**Comment by pijoter** [comment]
Mostly I need shits for decoding binary data from external sources (gps, data stream from floppy). It's very annoing to convert data to integer first (and then back to binary form). Rebol (at least R2) also support binary datatype shifts.

**Comment by 9214** [comment]
I proposed this back in summer, but realized that it would be more interesting (maybe even practical!) to have `shift` and `rotate` for all `series!` values.

**Comment by PeterWAWood** [comment]
Following the introduction of the [Red REP repository for enhancements and wishes](https://gitter.im/red/red?at=5adfeed527c509a7744a3dc8), this issue is being closed.

If you believe that your wish is still valid, please open a new issue for it in the new [red/REP repo](https://github.com/red/REP). It would help if you could include a link to this issue when opening an issue in the REP repository.

**Comment by dockimbel** [comment]
Rebol does not really support shifting on binaries (R2):
```
>> shift #{8000} 4
== #{0800}
>> shift #{8000} 8
== #{0000}
```

**Comment by endo64** [comment]
It shifts right each bytes separately:
```
>> shift #{FFFFFF} 7
== #{010101}
```
