### ISSUE TITLE
VIEW: field/text does not display any-string! but only string!

### ISSUE THREAD

**Issue by Oldes** [red/red#3193]
### Expected behavior

There should be visible content in the field even when `file!` or other `string!` based datatypes are used for field's `text` value.

### Actual behavior

Content is visible only when `string!` type is used.

### Steps to reproduce the problem

```
view/no-wait [f: field]
f/text: what-dir
probe f           ;- you may notice that f/text is holding a value of file! type 
do-events         ;- but the field appears to be empty
```

### Red version and build date, operating system with version.

0.6.3

**Comment by dockimbel** [comment]
Agreed, the current implementation for `/text` is minimal, extending it to `any-string!` is welcome.

**Comment by meijeru** [comment]
A simple `to-string` would perhaps be enough??

**Comment by dockimbel** [comment]
That's expensive, and that would reset the ownership flag of the series. A `as-string` would be way more efficient, but may not be very clean.

**Comment by meijeru** [comment]
Does `as-string` reset anything else than the type bits in the value slot? If not, it looks clean enough to me.

**Comment by PeterWAWood** [comment]
Following the introduction of the [Red REP repository for enhancements and wishes](https://gitter.im/red/red?at=5adfeed527c509a7744a3dc8), this issue is being closed.

If you believe that your wish is still valid, please open a new issue for it in the new [red/REP repo](https://github.com/red/REP). It would help if you could include a link to this issue when opening an issue in the REP repository.
