### ISSUE TITLE
Arbitrary Code Execution in Red macros?

### ISSUE THREAD

**Issue by iceflow19** [red/red#3216]
While I know this may be a tad premature to worry about things like this with since Red is still alpha, but I have no doubt this topic would have come up at some point. Since neither the Red nor the Rebol runtime running the macros are sandboxed, all it takes is a malicious source code file to allow for remote code exploits. See attached code, you can both access remote internet resources and executed shell code locally, more than enough to make a machine vulnerable.

What are the dev team's plans on this matter. Is there any way to combat this currently or will it take running the compiler fully on Red to address this?

```red
Red []
#do [
    write %test.out read http://www.json.org/
    call/output [dir %/c/windows] %test2.out
]
```

**Comment by dockimbel** [comment]
A Red macro is just Red or Rebol code evaluated at compile time (or at runtime when called from interpreter). Red macros are part of your source code, so you are already running arbitrary code (if you are not the source code author).

In your above example, the `#do` forces the evaluation of the argument block at preprocessing time. If you remove `#do [...]` wrapping, it will run the same code at run-time. Why do you think macros present a particular threat compared to "regular" code?

**Comment by iceflow19** [comment]
I am aware of the definition of a macro. My question is one of expectation and extent. Ignoring runtime preprocessing for right now, when one runs an executable there's the expectation of risk that comes with it. But with macros, I question if there is the same expectation. For programmers coming from other languages, I feel that they would assume that macros should **_only_** be able to act on the program's code.

That gives an expectation of security to the compilation process, minus of course any build scripts that might be involved. When I compile a C program, I don't expect it to be able to do my taxes. Macros should be either more sandboxed or more transparent to the user when they try to access resources outside of the scope of the code of the program, upon which they're supposed to mutate.

**Comment by greggirwin** [comment]
Sandboxing and security will come. Comparing to Lisp is better than comparing to C in Red's case.  Remember that Red is always data, and that inputs to a macro may not be your "program's code". It could be data scraped from, or generated somewhere else. If that data is tax rules combined with your personal information, where do we draw the line between what is done with preprocessing versus what is defined in the program? That is, what specifically should we disallow?

**Comment by iceflow19** [comment]
@greggirwin Point taken. Red's macros are more powerful.

>  It could be data scraped from, or generated somewhere else.

My issue is more with the capacity to write and execute external resources, rather than read from them.

**Comment by greggirwin** [comment]
This is an interesting area. Macros execute in their own context, so we could potentially limit things to enforce security aspects, but it might be much more complex if you want to rule out *all* possible risks, because Red is so flexible. That is, if you just think of macros as all of Red executing at a different time, in a different context, as soon as you want to lock it down, you have to lock it down hard, which might make them far less useful. 

Let's come back to the basic question of security. If we lock down macros, but you can still run Red, what have we gained? We should really set up docs, rules, and security features to you can't run untrusted code in either context with full authority, yes?

**Comment by BrianHoldsworth** [comment]
I feel like we should have already learned the lesson from previous sandboxed languages/runtimes that security is a system concern that can’t be adequately addressed in languages/runtimes. It’s a matter of education and diligence amongst programmers. The governing authority that manages the language/runtime can and should help, PRIMARILY through promotion of education and diligence amongst programmers.

Programmers need to understand the default security model that Red (or any language/runtime) provides, but they don’t need it to be a particular model.

**Comment by greggirwin** [comment]
Something we're learning as we look at the Red/C3 design, and lessons from Solidity, is that we should make it easy to be safe by default. If you step outside, it's up to you to know what you're doing.

**Comment by BrianHoldsworth** [comment]
That's right. But you are talking about language requirements of Blockchain Programmers developing smart contracts. They will most likely expect a different default security model than other Red Programmers.

As you are alluding to, it comes back to educating the programmers so they can understand and be appropriately diligent.

My simplistic and naive understanding of Red/C3 is that it is a DSL implemented using Red. As such, it will be implicitly defined how and whether the Blockchain Programmer can "step outside" I.e. by extending the DSL, right? If so, then that is a good thing and an important "feature", because it will help guide programmer understanding about how to both stay in a safe "sandbox" and how/when they play outside of it.

**Comment by greggirwin** [comment]
Red/C3 will be a DSL, yes, but it will likely be *very* tightly constrained, highly declarative, and not extensible. Not hard rules as the design is not set yet, but a primary goal there is security, which is different from Red, and it also has to run on blockchain VMs, which have very different execution environments. That is, it will compile to blockchain VM opcodes, limit runtime, and only access local state. Stepping outside moves into the realm of oracles, in blockchain parlance, which has yet to be determined as support for that varies by blockchain.

**Comment by greggirwin** [comment]
If you're familiar with http://www.rebol.com/docs/words/wsecure.html, there will likely be inspiration drawn from that approach for Red.

**Comment by BrianHoldsworth** [comment]
I think REBOL 'secure' is pretty nice. It is easy to understand and use.

But to the point of the OP, nothing in the one page Doc that is linked educates the programmer as to the perils of 'secure' if the environment/system that their Red app inhabits allows code injection attacks.
