### ISSUE TITLE
Wish: Multiselection in `text-list`

### ISSUE THREAD

**Issue by toomasv** [red/red#3224]
### Expected behavior
Shift-select selects consecutive indexes into block and returns it as `face/selected`.
Ctrl-select selects individual indexes into block and returns it as `face/selected`.
`event/picked` (which doesn't work right now) would return single index as integer.
`face/selected` might thus be integer or block.
### Actual behavior
Selecting `text-list` items doesn't react on `ctrl` and `shift` keys.
### Red version and build date, operating system with version.
W10

**Comment by PeterWAWood** [comment]
Following the introduction of the [Red REP repository for enhancements and wishes](https://gitter.im/red/red?at=5adfeed527c509a7744a3dc8), this issue is being closed.

If you believe that your wish is still valid, please open a new issue for it in the new [red/REP repo](https://github.com/red/REP). It would help if you could include a link to this issue when opening an issue in the REP repository.
