### ISSUE TITLE
rejoin applies function to all occurencies of variable

### ISSUE THREAD

**Issue by nickkoro02** [red/red#3226]
It may be the expected behaivor, but its rather strange and undocumented.

### Expected behavior
```
i: "bla"
rejoin [i reverse i]    ; => "blaalb"
```
### Actual behavior
```
i: "bla"
rejoin [i reverse i]    ; => "albalb"
```
### Steps to reproduce the problem
See above.
### Red version and build date, operating system with version.
`Windows 10 x64`
`Red for Windows version 0.6.3 built 12-Aug-2017/21:38:44+02:00`

**Comment by 9214** [comment]
You're reversing string in-place.
```Red
>> i: "12"
== "12"
>> rejoin [i reverse i]
== "2121"
>> reverse i
== "12"
>> rejoin [i reverse copy i]
== "1221"
```

**Comment by greggirwin** [comment]
We started adding "(modified)" to some doc strings, as an experiment (started with R2), to see if it helped. e.g. `sort` and `remove-each` have it today. The issue is that modifying is the case for many, maybe most, series args. It's not that we shouldn't include this info somewhere. Just a matter of whether it should be in the standard doc string or extended docs. Either way we need to defined a convention to keep it consistent.
