### ISSUE TITLE
Windows Defender reports gui-console.exe as Trojan

### ISSUE THREAD

**Issue by BeardPower** [red/red#3263]
### Expected behavior
Threat-free executable.
### Actual behavior
Windows Defender reports `gui-console.exe` as `Trojan:Win32/Dorv.D!rfn`.
### Steps to reproduce the problem
Checkout any branch of RED.
Fire up REBOL/View.
Compile the gui-console with: `do/args %red.r "-r -t Windows %environment/console/gui-console.red"`

Windows defender will report the threat.
### Red version and build date, operating system with version.
Red for Windows version 0.6.3 built 15-Mar-2018/13:22:46+01:00

Microsoft Windows [Version 10.0.16299.309]

**Comment by dockimbel** [comment]
Could you please fill a false positive report there? https://www.microsoft.com/en-us/wdsi/filesubmission

They require some extra infor, like the Defender definitions version number.

**Comment by DideC** [comment]
May be it will be hard to keep it not tagged as "threat" as Red is a moving target : it evolves regularly for those who download regularly.

Just tried the last one and I also get the Windows Defender alert.
Restoring the quarantine program works.

**Comment by greggirwin** [comment]
@dockimbel, should we add an AV label for issues?

**Comment by BeardPower** [comment]
@dockimbel Sure, sending is done.

**Comment by 9214** [comment]
@greggirwin speaking of AV label, I already have most of the false-positive-related tickets collected.

**Comment by greggirwin** [comment]
Excellent @9214!

**Comment by dockimbel** [comment]
@greggirwin If you think it would help, we could have a `type.AV` one.

**Comment by greggirwin** [comment]
I do think `type.AV` would be useful. As long as it's not confused with Audio-Visual. I see this ticket at `status.AV` now, which works for me.

**Comment by greggirwin** [comment]
Interestingly, Security Essentials (Win7) just asked me today to send the console binary I had just built for analysis.

**Comment by 9214** [comment]
@greggirwin I think vendors share their signature DBs somehow.

**Comment by DideC** [comment]
Security Essentials (Win7 and earlier) = Windows defender (Win10)
So same vendor: M$

**Comment by RnBrgn** [comment]
Same result with today's Red build on Windows 10 . 

![image](https://user-images.githubusercontent.com/16709809/38003116-0d542a54-3204-11e8-86ca-9e2aecb77c3e.png)

**Comment by 9214** [comment]
There are a couple of tickets **†‡** tagged with [`type.AV`](https://github.com/red/red/issues?q=is%3Aissue+label%3Atype.AV) on the issue tracker, and some of them (including this one) are still opened.

As of today, nightly build of the Red toolchain and GUI/CLI consoles compiled from sources (master branch) have the following VirusTotal scores:

| Binary | Score |
|:-|:-|
| [Toolchain](https://www.virustotal.com/gui/file/e68cb9bd131bda6a53bda1e25227bd899a14983302611434c7d4e8e2de0875b5/detection) | 0/72 |
| [GUI console](https://www.virustotal.com/gui/file/6c917eac7bcacd1e47214d1a724c386055053b33a577ec47d4fb1dbe3314c022/detection) | 13/72 |
| [GUI console uncompressed](https://www.virustotal.com/gui/file/58096f9c7874c9d369f57696e2cfdc7bd3f1817961aed258fc6eca5a42f22996/detection) | 17/72 |
| [CLI console](https://www.virustotal.com/gui/file/621ecf4ff0cab28f011397e9fd7724c24515e5d46c412ca07fefb19077eca5af/detection) | 13/72 |
| [CLI console uncompressed](https://www.virustotal.com/gui/file/d80a02d09c5f487b735db7454ad25499397df206c98cb6416653a139843880fd/detection) | 8/72 |

I hazard a guess that triggered scanners check only:

* Signatures (Rebol Technologies vs. Red Foundation);
* PE layout and perhaps DATA section entropy.

I leave it to others to decide if such metrics are reliable and if these scanners can be trusted (note that with consoles compilation sources are the same, but compression makes score go either up or down).

False-positives are rather generic and keep resurfacing from time to time, always without even a slightest indication of what we did (or did not) to cause them. Our hands are tied without any form of feedback from AV vendors/scanners, and there's little we can do except for shooting in the dark and hoping for the best.

We have a dedicated [wiki page](https://github.com/red/red/wiki/%5BNOTE%5D-Anti-virus-false-positives) that describes the problem in a more detail and points out solutions that proved to be effective, ready to be used by anyone concerned.

So, I propose we close the pending tickets **†** and refer people to that page (and this message) in the future.

I also propose we keep collecting false-positive reports as data points, to harness stats and draw some sort of a timeline (e.g. to proove that there's zero correlation between false-positives alarms and changes in the codebase, and that the majority of them are caused by poor AV heuristics) — but since there's no one-size-fit-them-all solution to such issues, they should be closed with a reference to the above-mentioned wiki page.

---

**†** #3584 #3263 #3260 #2968 #2903 #2399
**‡** #3802 #3347 #3294 #3255 #3137 #3026 #2317 #2020 #1841 #500

**Comment by greggirwin** [comment]
Done.
