### ISSUE TITLE
Transpile to js / target browser

### ISSUE THREAD

**Issue by jbshirk** [red/red#3304]
I have been telling people that Red is THE full stack language of the future. However I have been unable to find how Red targets the browser, I assume via transpilation to JavaScript. If this capability exists, it should be easier to find in the docs.

**Comment by greggirwin** [comment]
@jbshirk, what @9214 said about using Gitter first is the most important thing. 

We do have plans for how browser support can be added--there is no single right way of course--but it's not a short term milestone or high priority. Whether the browser falls under our "full stack" dominion is another question. Compiling to JS is only part of the equation, as there's the UI to consider. Red has a cross platform GUI system, and the browser uses HTML rather than native controls from the OS.
