### ISSUE TITLE
Allow compilation of Static libRed

### ISSUE THREAD

**Issue by svnpenn** [red/red#3417]
Currently you can build a Shared libRed like so:

~~~
red build libRed
~~~

however it appears Red has no option to build a Static libRed.

**Comment by svnpenn** [comment]
https://github.com/red/red/issues/3412

**Comment by greggirwin** [comment]
Thanks for the ticket @svnpenn. We've set up https://github.com/red/rep/issues specifically for wish tickets like this. If you could add your wish over there, that would be great.

**Comment by svnpenn** [comment]
@greggirwin its not a wish, its a bug/issue - shared and static libraries should **both** be "first class citizens". if you disagree - well then we just disagree

but i am not posting an issue that says that this is a "wish" - or posting to a repository of "wishes", on principle. if *you* wish to do that and link here - then by all means

good day

**Comment by svnpenn** [comment]
@PeterWAWood in case it wasnt clear, im not talking about some 3rd party
library. i am talking about the Red library itself, libRed.

For any who my visit this page in frustration - an alternative language is
http://github.com/nim-lang/Nim. It allows fast compilation - even static:

~~~
$ nim c --gcc.exe:x86_64-w64-mingw32-gcc \
> --gcc.linkerexe:x86_64-w64-mingw32-gcc hello.nim
Hint: used config file 'C:\nim-0.18.0\config\nim.cfg' [Conf]
Hint: system [Processing]
Hint: hello [Processing]
CC: hello
CC: stdlib_system
Hint:  [Link]
Hint: operation successful (41816 lines compiled; 4.446 sec total;
121.402MiB peakmem; Debug Build) [SuccessX]
~~~

**Comment by greggirwin** [comment]
@svnpenn, using Red's issue tracking to promote another language is...not nice. If you wonder why I deleted your message, that's the reason. If you want all languages to be equal, are you also posting on their forums that they should match Red, feature for feature? I'm not trying to be mean, but some of our best people spent a significant amount of time explaining things to you, but you don't seem to want to listen.

**Comment by 9214** [comment]
To give some context to the edited version of @svnpenn's message.

It was explained to him by at least 4 different people:
1. **Why comparing Red toolchain and GCC by compilation speed makes absolutely no sense** - because the former one is a very high-level programming language in the alpha stage of development, which relies on a throw-away bootstrap compiler with no optimization layers, and the latter is 20-something years old ~~mammoth~~ highly tuned pipeline for a low-level language (which is C). If you want a fair comparison - pick Red/System (a low-level C-like DSL) instead.
1. **Why toolchain does not offer options for static compilation** - because, see p.1, current compiler is a throw-away one, and will be dropped off once bootsrapping phase is complete. Spending time on integration of proposed feature is impractical, and also requires a significant amount of work to be spend on extending the linker for each target file format.
1. **How OP can refine his workflow in the absence of the proposed feature** - by using a shared version of libRed instead, or by relying on the interpreter during development, thus omitting long compilation times entirely and speeding up the development process by at least the factor of two.

All of the explanations and suggestions were either ignored or dismissed, while conversation itself was marked as ['going nowhere'](https://gitter.im/red/red?at=5b1bf8f614d4bc146e792f8f). 
Instead of creating a feature request in the [appropriate repository](https://github.com/red/rep/issues), OP continued with a [previously failed attempt](https://gitter.im/red/red?at=5b1bec793516592752f74de3) at programming languages flamewar. The message was deleted (as can be seen above) with a prompt warning by @greggirwin. In spite of that, OP continued his line of action by updating the original message, with a content which was indicated by @greggirwin as inappropriate.

Without giving this issue a highly political flavor, I'll say that it's not a nice thing to do. Your feature request, @svnpenn, will be implemented in post-1.0 versions of Red toolchain (as it was planned anyway), but your attitude will hardly make you a welcome guest in our community.

**Comment by cup** [comment]
https://github.com/red/REP/issues/46

**Comment by cup** [comment]
I am willing to donate $800 if this can be implemented, thank you!

**Comment by dockimbel** [comment]
Seems like the last post is a [spam](https://github.com/cup/autumn/commit/515975fa9c802d88ca0507b2f441b4301e71cbdd). The author got [banned from Lobster](https://lobste.rs/u/cup).
