### ISSUE TITLE
make path! <spec> is insufficiently constrained

### ISSUE THREAD

**Issue by meijeru** [red/red#3463]
### Expected behavior
`type? load mold make path! <spec>` should be `path!` when `<spec>` conforms to the rules for path components, and give an error otherwise
### Actual behavior
```
>> type? load mold make path! [a b]
== path!
>> type? load mold make path! [a]
== word!
>> type? load mold make path! []
== block!
>> type? load mold make path! [1 2 3]
== date!
```
In other words, using `make` one may produce `path!` values that cannot be properly evaluated as paths. The case of single or zero compenent paths has been discussed already, but the paths starting with an integer are even more problematic.
### Steps to reproduce the problem
execute above code
### Red and platform version
```
all
```

**Comment by bitbegin** [comment]
so `make path! []` and `make path! [1 2 3]` should give an error?

**Comment by meijeru** [comment]
For me yes. Others may argue that in certain dialects there is a use for such strange paths, but for me, blocks would serve that purpose equally well.

**Comment by bitbegin** [comment]
but i also think "1/2/3" can be useful for some situations.

**Comment by greggirwin** [comment]
So, in Red, do we define a hard and fast, universal rule about load/mold being exact inverses? Put another way, knowing it's possible to produce something that doesn't do that, do we block all other uses? The 3 number case is unique in its conflict with dates. 

Do we lock things down, or fix it with language and say "Here's how this works. You've been warned." ? 
In some ways it's a question of when we catch the problem. e.g.
```
>> load mold to issue! "%"
*** Syntax Error: invalid issue! at "#%"
*** Where: do
*** Stack: load  
```
And, an unrelated, much uglier question...do we want to keep that date format? I know. I know. It's so common. I'm afraid we may be stuck with it.

**Comment by greggirwin** [comment]
As even more of a Devil's Advocate (it's late and I'm feeling ornery), what's the shortest way to *intentionally* create a date of the form mm/dd/yyyy or yyyy/mm/dd, given 3 values?

**Comment by dockimbel** [comment]
> So, in Red, do we define a hard and fast, universal rule about load/mold being exact inverses? Put another way, knowing it's possible to produce something that doesn't do that, do we block all other uses? 

That's a big question. Having a fully symetrical `load` and `mold` would mean forbidding a lot of possible values that would not have a proper literal representation. My current position is that the syntactic rules should not restrict the possible space for allowed values, because then building composite values can become very difficult and would put some new burden on the users. Moreover, it might be very costly and/or very complex to implement such restrictions, and it also would look like an artificial limitation of the language semantics. 

Redbin will provide a fully re-loadable representation of the Red values, but in binary format, not in human-readable format, because that would not be doable (the Rebol's construction syntax cannot cover all the properties of each datatype, like binding for example).

**Comment by greggirwin** [comment]
@meijeru, given @dockimbel's comment, can we close this ticket, and make notes of what we need to address in docs?

**Comment by meijeru** [comment]
I suppose so, but some of these considerations should not only go into the docs, but also inform the design of the construction syntax.

**Comment by greggirwin** [comment]
Sure. Thanks.
