### ISSUE TITLE
`unset 'none` kills console

### ISSUE THREAD

**Issue by toomasv** [red/red#3506]
### Expected behavior
`unset 'none` throws error or something
### Actual behavior
`unset 'none` silently kills console.
Same with e.g. `unset body-of #(a: none)`.
### Steps to reproduce the problem
As above
### Red and platform version
```
-----------RED & PLATFORM VERSION----------- 
RED: [ branch: "master" tag: #v0.6.3 ahead: 828 date: 12-Aug-2018/3:37:05 commit: #6229b573535ea841cecb8d326b9905d91ad91679 ]
PLATFORM: [ name: "Windows 10" OS: 'Windows arch: 'x86-64 version: 10.0.0 build: 17134 ]
--------------------------------------------
```

**Comment by meijeru** [comment]
This is very much related to re-assigning pre-defined words. There has been an extensive discussion about this already.

**Comment by toomasv** [comment]
@meijeru Should I delete this? Also connected to https://github.com/red/red/issues/3338

**Comment by meijeru** [comment]
#3338  has been resolved, and thus the application of `unset` should not anymore give a crash in general. The fact that unsetting pre-defined words gives a crash is not a matter of wrong programming of the toolchain, but inevitable since the toolchain, which is (partially) written in Red, depends for its operation on pre-defined words having their original meaning. I would leave it to the Red team to dismiss this, though. @dockimbel @gregg

**Comment by greggirwin** [comment]
This is interesting. Let's leave it open for the moment, and see if we can find out exactly why it crashes. It may be a systemic problem, not easily solved, or it may just be something simple. Rebol doesn't crash if you do this, but certainly anything written to expect `none` won't work anymore.

**Comment by meijeru** [comment]
I compare this to the redefinition of `equal?` which made the toolchain crash the first time an equality was tested (#360). Then @dockimbel was able to put the finger on it exactly, but it might be onerous to do the same thing for `none` and would not give more than intellectual satisfaction, if you ask me...

**Comment by bitbegin** [comment]
this is not same reason as #3338, but still a big problem that i want to fix.

**Comment by bitbegin** [comment]
this is not same reason as #3338, but still a big problem that i want to fix.

**Comment by bitbegin** [comment]
this is not same reason as #3338, but still a big problem that i want to fix.

**Comment by bitbegin** [comment]
Not same reason as #3338, but still a big problem that maybe we can fix.

fix steps:

1. add a protect flag for data's header field, maybe bit 14 for this flag

2. when a word! is created, set this flag to "unprotect" status.

3. when a word! need to be set, check this flag, if it's "unprotect", it can be set normally, otherwise fire error!

4. improve protect and unprotect function to set this flag

5. we can set Red key words to "protect" status after runtime loading finished.


In step 5, if we protect Red key words, we cannot unset these words, it will be different from Rebol action.
To avoid this situation, we should distinguish Red key words from key words used in Red evironment.

Maybe step 5 meet current needs.

**Comment by qtxie** [comment]
Actually it is not a crash in this case, just the console exit.
As the console itself is a Red program, once `None` being unset, all the code rely on it will be broken. 
This is the [main loop](https://github.com/red/red/blob/master/environment/console/engine.red#L222-L228) in the console engine:
```
forever [
	eval-command ask any [
		cue
		all [string? set/any 'p do [prompt] :p]
		form :p
	]
]
```
After `None` is unset, `eval-command` will throw an error, which will exit the `forever` loop. So a simple fix is to add a `try` block around `eval-command`.
 ```
forever [
	try [
		eval-command ask any [
			cue
			all [string? set/any 'p do [prompt] :p]
			form :p
		]
	]
]
```

**Comment by dockimbel** [comment]
Protection flags and `protect/unprotect` natives is the solution for such cases, but that is planned for 0.8.0, so I'll close this ticket as "deferred".
