### ISSUE TITLE
FIND/MATCH/REVERSE is not working

### ISSUE THREAD

**Issue by Oldes** [red/red#3609]
**Expected behavior**
This is how it was working in Rebol2:
```
>> find/reverse/match tail "abc" "abc"
== ""
```
**Actual behavior**
```
>> find/reverse/match tail "abc" "abc"
== none
```

**Comment by endo64** [comment]
It should at least able to find "abc" in the middle

```
>> find/reverse/match probe back back back tail "abcabcabc" "abc"
"abc"
== none
```

**Comment by qtxie** [comment]
I don't think Rebol2 support it. It works the same as `/tail` in Rebol2:
```
>> find/reverse/match tail "abcd" "abc"
== "d"
>> find/reverse/tail tail "abcd" "abc"
== "d"
```

**Comment by greggirwin** [comment]
`Find` is worthy of its own docs and many examples. I imagine the community resources cover it to at least some extent, but don't have time to look at them right now.

**Comment by dockimbel** [comment]
`find/match/reverse` should always return `none` in Redbol, because those modes are incompatible. See my explanations [there](https://github.com/red/red/issues/3339#issuecomment-450477223).

@Oldes The above behavior of Rebol2 looks like a bug to me, that occurs when using a series for the pattern to search:
```
find/reverse/match tail "abc" "abc"
== ""
find/reverse/match tail "abc" #"b"
== none
```
As you can see, the right result (`none`) is returned when passing a character instead of a string as argument.

In R3, this bug has been fixed:
```
find/reverse/match tail "abc" "abc"
== none
```

@qtxie Please revert your changes that are covering this ticket.
