### ISSUE TITLE
hash! doesn't accept set-path notation (apart from numeric indexes)

### ISSUE THREAD

**Issue by hiiamboris** [red/red#3720]
**Describe the bug**

```
>> x: make hash! [a: 1]
== make hash! [a: 1]
>> x/a: 2
*** Script Error: cannot set none in path x/a:
*** Where: set-path
*** Stack: 
```

**Expected behavior**

Same works for map! and block!:
```
>> x: make block! [a: 1]
== [a: 1]
>> x/a: 2
== 2
>> ? x
X is a block! value.  length: 2  [a: 2]

>> x: make map! [a: 1]
== #(
    a: 1
)
>> x/a: 2
== 2
>> ? x
X is a map! with the following words and values:
     a  integer!      2
```

**Platform version (please complete the following information)**
```
Red 0.6.4 for Windows built 5-Jan-2019/4:37:59+03:00 commit #1c0642e
```

**Comment by meijeru** [comment]
This is not true when the hash component to be selected is indicated by a `word!` instead of a `set-word!`.
```
>> x: make hash! [a 1]
== make hash! [a 1]
>> x/a
== 1
>> x/a: 2
== 2
>> x
== make hash! [a 2]
```

**Comment by qtxie** [comment]
FYI
In Rebol2:
```
>>  x: make block! [a: 1]
== [a: 1]
>> x/a
** Script Error: Invalid path value: a
** Near: x/a
>> x/a: 2
** Script Error: Invalid path value: a
** Near: x/a: 2
```
In Rebol3: 
```
>>  x: make block! [a: 1]
== [a: 1]
>> x/a
== 1
>> x/a: 2
== 2
```
I'm not sure which is better.

**Comment by greggirwin** [comment]
It seems like it should work to me, unless @dockimbel made it an intentional design choice, in which case he can tell us the reason.

**Comment by dockimbel** [comment]
Seems like an implementation issue in hash! to me. I agree on the need for consistency between `block!` and `hash!`, but `map!` has specific semantics, so cannot be compared here with the two others (maps will normalize words to set-words):
```
>> #(a 1)
== #(
    a: 1
)
```

With regard to the path access and the relaxed behavior, keep in mind that being able to select accurately words with the right type is then lost using paths:
```
>> x: [a 1 a: 2 'a 3]
== [a 1 a: 2 'a 3]
>> w: 'a
== a
>> x/:w
== 1
>> w: quote a:
== a:
>> x/:w
== 1
>> w: quote 'a
== 'a
>> x/:w
== 1
```
One would need to use `select/case` in order to distinguish words by type in such case. `/case` uses a stricter comparison mode (`strict-equal?`), so will do the job here. Though the `/case` naming here becomes unrelated and a `/strict` refinement would be better. So this is an unresolved design point for now, the different options are:

1. Keep using `/case` to cover case-sensitive search + strictness.
2. Rename `/case` to `/strict` and loose a bit of consistency with other functions' `/case` refinement.
3. Keep `/case` and add `/strict`, and clearly separate the two modes, though that would add a new refinement to an already overloaded function spec.

**Comment by hiiamboris** [comment]
@dockimbel looks like `/case` isn't even needed:
```
>> x: [a 1 a: 2 'a 3]
== [a 1 a: 2 'a 3]
>> select/same x quote a:
== 2
>> select/same x quote 'a
== 3
```

**Comment by qtxie** [comment]
@hiiamboris The `/case` refinement is mainly for this case:
```
select/case ["abc" 1 "Abc" 2 "ABC" 3] "Abc"
```

**Comment by dockimbel** [comment]
@hiiamboris Indeed, I forgot we added `/same` to `select`.

@qtxie Red relies on the same behavior as R3 for this case. Can you implement it in `hash!`?

**Comment by qtxie** [comment]
@dockimbel `hash!` support same already.
```
>> x: make hash! [a 1 a: 2 'a 3]
== make hash! [a 1 a: 2 'a 3]
>> query quit quit-return quote
>> select/same x quote a:
== 2
>> select/same x quote 'a
== 3
```

**Comment by dockimbel** [comment]
@qtxie I meant the behavior for paths on blocks described at the beginning of the ticket. Can we easily support it for hash too?
