### ISSUE TITLE
[Core] object on-change* looks away most of the time

### ISSUE THREAD

**Issue by hiiamboris** [red/red#3804]
**Describe the bug**

Given an object
```
o: object [
	i: 1
	on-change*: func [w o n] [print [" ***" w "changed" o ">" n]]
]
```
I want it to know when `i` value is changed.
Currently, only the set-path notation is detected:
```
do probe [o/i: o/i + 1]
do probe [set in o 'i o/i + 1]
do probe [do bind [i: i + 1] o]
```
Results in:
```
[o/i: o/i + 1]			; detected
 *** i changed 1 > 2
[set in o 'i o/i + 1]		; skipped
[do bind [i: i + 1] o]		; skipped
```
This limits the applicability of the `on-change*` a lot.

**Expected behavior**

I expect every change (except by `set-quiet`) to be detected

**Platform version (please complete the following information)**
```
Red 0.6.4 for Windows built 5-Mar-2019/0:09:36+03:00 commit #53b5b37
```
:point_up: [March 5, 2019 10:48 PM](https://gitter.im/red/bugs?at=5c7ed2a20966d912042ae839)

**Comment by greggirwin** [comment]
@dockimbel will have to speak to whether this is by design. Your suggestion makes sense, and may just be a bug. There is a bit involved, between stack, `object/set-many` and `object/on-set-defined?`, versus the context funcs for setting values.

This works, as the check for object in `set` catches it.
```
>> set o [i: 2]
 *** i changed 4 > i
== [i: 2]
```

**Comment by Oldes** [comment]
My guess is, that version 2 and 3 would be too difficult to implement (if not impossible) as opposite to version 1, which is quite easy as the reporting is done on [eval-path](https://github.com/red/red/blob/53b5b37b3fd37a2a4b88452b2cc90a7e89c5f428/runtime/datatypes/object.reds#L1129)

**Comment by dockimbel** [comment]
The detection on set-paths only is by design. 

Having a generic detection on every word set would be probably too expensive and significantly affect the overall performances of Red (though, this has not been measured, so it's just an educated guess at this point). We can try to extend it when the next iteration on object events will happen, and see how much performance is lost in various common use-cases.

Moreover, in the above path version case, the compiler can understand such code pattern and generate static calls to object events, but there's no way for the compiler to do the same for the other non-path cases.

**Comment by hiiamboris** [comment]
Just for the info, my use case was like this.
I have a block (tiny DB) with lots of values `[a b c  a b c  a b c ...]`, sort of like reactivity/relations. And I wanted a simple lookup object & a function on that object that, when any of a/b/c is set - will fill in the other two. Like `lookup [a: 1 b]` would detect a change in `a`, perform a search and change `b` and `c` and then return the new `b`. Simple idea, but it requires me to preprocess the block and replace all set-words with set-paths or it won't work.

**Comment by hiiamboris** [comment]
Worthy of note that the above does work with the reactors (which in turn are supported by R/S), and thus I find it unfair that one cannot build his own reactivity in pure Red that is not based on the `reactor!` type:
```
o: make reactor! [
	i: 1
	on-change*: func [w o n] [print [" ***" w "changed" :o ">" :n]]
]

do probe [o/i: o/i + 1]
do probe [set in o 'i o/i + 1]
do probe [do bind [i: i + 1] o]
```
Output:
```
 *** on-change* changed ?function? > ?function?
[o/i: o/i + 1]                                 
 *** i changed 1 > 2                           
[set in o 'i o/i + 1]                          
 *** i changed 2 > 3                           
[do bind [i: i + 1] o]                         
 *** i changed 3 > 4                           
```

**Comment by greggirwin** [comment]
Why do you consider the current model unfair? As @dockimbel noted, this limitation could be lifted in the future, but all designs have tradeoffs, whether they be privileged elements or performance. For example, you *could* build your own reactivity system, in pure Red, I imagine, but it wouldn't be compatible with the current one.

Given that it works with reactors, what limitation does it impose? That is, what *can't* you do, other than using a plan `object` instead of a `reactor!`?

**Comment by hiiamboris** [comment]
@greggirwin True. I seems I can build my own reactivity based on `reactor!` by overriding it's `on-change*` value. ☻ But then what purpose does `object!/on-change*` serve if it can't be relied upon like `reactor!/on-change*`? I just don't understand designs that work *sometimes* or under very *specific conditions*. IMO they create more problems that they solve.

**Comment by greggirwin** [comment]
We should absolutely document, clearly, how object/on-change* works and its limitations. We can then decide if it's useful, because it works in the most common case, or look at disallowing it, because it will trip up too many people.

**Comment by dockimbel** [comment]
@hiiamboris 
> I find it unfair that one cannot build one's own reactivity in pure Red that is not based on the reactor! (or face!) type:

The reactivity framework exposed through `reactor!` and `face!` objects is entirely built in Red, so you can define freely your own reactive frameworks using the built-in `object!` events (that we will extend in the future with more events).

**Comment by dockimbel** [comment]
FYI, in both cases, it works fine when compiled... so it should be possible to make it work the same way in the interpreter.

**Comment by hiiamboris** [comment]
Here's a workaround to avoid reactors and use objects:
```
o: make object [on-change*: does []] [
	i: 1
	on-change*: func [w o n] [print [" ***" w "changed" :o ">" :n]]
]

do probe [o/i: o/i + 1]
do probe [set in o 'i o/i + 1]
do probe [do bind [i: i + 1] o]
```
```
 *** on-change* changed ?function? > ?function?
[o/i: o/i + 1]
 *** i changed 1 > 2
[set in o 'i o/i + 1]
 *** i changed 2 > 3
[do bind [i: i + 1] o]
 *** i changed 3 > 4
```

**Comment by dockimbel** [comment]
> Pure magic...

Stack corruption caused by providing an invalid `on-change*` handler which a wrong number of mandatory arguments. Arity needs to be checked and the event handler definition rejected if it's not compliant. This applies to all event handlers provided by the user and called from within the Red runtime.

I'll open a separate ticket for this one, as it's not related to the original topic.

**Comment by dockimbel** [comment]
> FYI, in both cases, it works fine when compiled... so it should be possible to make it work the same way in the interpreter.

Now supported in interpreter too, as a side-effect of fixing several object events issues.
