### ISSUE TITLE
`foreach-face` unexpected behavior

### ISSUE THREAD

**Issue by planetsizecpu** [red/red#3819]
Some findings on foreach-face last days:

1- Stack overflow when using `continue`  inside `foreach-face`:

![Finding1](https://user-images.githubusercontent.com/12875228/54350352-70c69780-464d-11e9-8069-ca19d22ac5e5.jpg)

2- `print` will modify values on objects:

![Finding2](https://user-images.githubusercontent.com/12875228/54350456-abc8cb00-464d-11e9-915f-b6d255de224f.jpg)

3- `return` inside `foreach-face` wont return a value:

; That loop works well and return none or value from face
`Ret: none
foreach-face cave [
    if face <> f [
        if overlap? face f [Ret: face/extra/name]
    ]
]
return Ret`

; That loop returns none or without value from face
`Ret: none
foreach-face cave [
    if face <> f [
        if overlap? face f [return face/extra/name]
    ]
]
return Ret`

**Comment by hiiamboris** [comment]
@planetsizecpu please provide code snippets for developers so they can reproduce the bugs.

**Comment by 9214** [comment]
1. Because `continue` interfers with internal `foreach` loop. Use `/with` with condition block instead.
1. I highly doubt that this has anything to do with `foreach-face`, which is just a virtual tree traversal.
1. `return` returns from `foreach-face`, which is a function.

None of this looks like a bug to me, and rather belongs to `/help`  or `/bugs` Gitter rooms. In the absence of any useful information (like minimal examples, Red version, actual code) I cannot see what we can do with this ticket.

**Comment by planetsizecpu** [comment]
Yes, I guess #1 and #3 are related to break of control, returning func before `foreach-face` exits, I have solved it by removing the break and checking out of the loop, but I thing it is worth to check is presence in code, don't you?
#2 is intriguing to me, because "OVERLAPS" text only appears on the line I wrote here, how the hell has got written on the object? maybe it is related to GC, I din't have time to test more by now, but I cant get it out of my mind, I have to dig a bit more in the weekend.
By now I don't want to upload the code to git, because I have to clean it a bit and set some funny comment right.

**Comment by endo64** [comment]
@planetsizecpu Please always keep the issue template's formatting and raise separate tickets for different issues. And of course it is always better to discuss on /bugs room before submitting an issue.

Also note the #`number` automatically references the issue/PR with ID `number` so you're referencing issue 1, 2 and 3 now, which can confuse the developers. Please edit you issue and remove the references.

Here is a test script:
```
Red [Needs: View]
win: layout [base "1" base "2" base "3"]
foreach-face win [probe face/text continue]
print "ok"
```

When I compile the above script with an older version of Red, the output is:
```
"1"
"ok"
```

With latest version (`date: 14-Mar-2019/17:49:29 commit: #43b26838` on Win10)
```
"1"

*** Runtime Error 98: assertion failed
*** Cannot determine source file/line info.
```

**Comment by planetsizecpu** [comment]
@endo64 Thx, I whas not aware of # meaning, I edited the issue, hand have it in account for next findings.
It is difficult to repeat the failure with just a bit of code snippet, I have sent the entire scripts along with the project files to @qtxie so he can check what the problem is.

**Comment by 9214** [comment]
@planetsizecpu instead of bothering one of the core developers personally, you should have tried to narrow down the problem by yourself and to reproduce it with minimal example(s), then report your findings back here, or at least extend the original report with information we've requested (Red and OS version, copy-pastable code, etc). "Difficult to repeat" likely means that your problem is a side-effect of your own mistake somewhere else in your code.

It is in your responsibility (as a contributor) and in your interests (as a developer) to provide meaningful and informative bug reports (which, at the very least, follow standard issue template and provide reproducible examples). Shifting this responsibility on developers only adds to the burden they already have, and postpones solution of your problem indefinitely.

**Comment by planetsizecpu** [comment]
I am sorry if I have not explained myself well. The code example that I have put above is the one that generates the failure, but I can not reduce it so much to reproduce it because it is being called by an on-time event that in turn depends on other events on-time that its they depend on the keys pressed by the user and the movement of the faces, all this code also handles about 50 bmp files, and I do not know how I can reduce it so that the fault is reproduced. That's why I've thought about sending it to @qtxie like on other occasions.
This is the problem, it is so complex that I can not reduce it and at the same time reproduce the fault, so I'm sorry if it's my fault.
If this can not be solved in this way, it is better to close the ticket, but over time someone may replay the same fault and report it.
