### ISSUE TITLE
running out of memory when MOLDing or FORMing deeply nested face

### ISSUE THREAD

**Issue by 9214** [red/red#4118]
**Describe the bug**
Title.

**To reproduce**
```red
layout [foo: base center font-size 0 on-down [probe '>>> form face probe '<<<]]

view make face! [
    type: 'window
    size: foo/size + 20
    pane: reduce collect [loop 44 [keep copy foo]]
]
```
Usage of `center` and `font-size` creates `para!` and `font!` objects, respectively, which contribute to the issue.

Click on base, and, after GUI stutter, observe the console output:
```
>>>
*** Internal Error: not enough memory
*** Where: form
*** Stack: view do-events do-actor do-safe
```

**Expected behavior**
```
>>>
<<<
```

**Platform version (please complete the following information)**
```
Red 0.6.4 for Windows built 2-Nov-2019/20:40:59+01:00 commit #1d32938
```

**Comment by hiiamboris** [comment]
Curiously, the original snippet doesn't reproduce the issue anymore. Since Dec 20th build you have to use `loop 60` or more.

**Comment by 9214** [comment]
https://github.com/red/red/commit/bba311f2 ?

**Comment by hiiamboris** [comment]
Yes, indeed. The older builds topped 850MB, while the new ones reach 1.7GB before they fail. And never recycle ;)

**Comment by dockimbel** [comment]
I have found no bug in the cycle detection code. The huge memory consumption is caused by the attempt at serializing the huge graph created by the face tree, mainly caused by the `/parent` facets in `face!`, `font!` and `para!` objects.

I propose the `/parent` blocks be kept at tail all the time by the View engine, so that we keep the serialization output minimal.

**Comment by hiiamboris** [comment]
This is related to https://github.com/red/red/issues/4464 discussion

**Comment by dockimbel** [comment]
> What I'm doing in Spaces is /parent, /cache are words, 

So you are cluttering the symbol table just for the sake of avoiding direct object references? That does not look like a good solution.

**Comment by hiiamboris** [comment]
Not so many symbols really. Bigger issue is I can't use paths to access such words content. But still it was worth it so far. When I see e.g. `parent:  'cell` in mold output that tells me so much more than `parent: make object! [...]`.

**Comment by dockimbel** [comment]
>  and rewrite mold instead.

I guess you know by now what are the chances that such deep modification there would be accepted to the main repo without prior discussion and approval.

**Comment by hiiamboris** [comment]
Never said I would push it, I may rewrite it just for local use in Spaces. Problem with `dump-face` is what if a space appears in another data somewhere, e.g. in a block? I will need a `mold` that accepts all datatypes, but when it meets a space or face object it outputs it's name or name+part of content depending on the already-reached output nesting level. So far such rewrite was challenging enough to avoid it.

**Comment by hiiamboris** [comment]
Then it will not be called `dump-face` but some `probe` variant, which it will be, as it will have to accept any-list and more :)

**Comment by hiiamboris** [comment]
I agree, my solution was ad hoc, and I after all decided that we should work on our tools, not find workarounds for their issues. I had [success](https://codeberg.org/hiiamboris/red-spaces/src/branch/internalized-name/design-cards/words-or-objects.md) with `mold` eventually, but `form` is just out of my reach, as it's too pervasive. And the above fix doesn't solve the root issue, only works around it. So this issue is deeply tied to https://github.com/red/REP/issues/134 and should be seen as a debug facilities design issue.
