### ISSUE TITLE
Red after compile incorrectly flagged as virus by Webroot

### ISSUE THREAD

**Issue by aberusugi** [red/red#4264]
Just a headsup:

Threat List:
GUI-CONSOLE-2018-11-22-8164.EXE, W32.Adware.Gen, %appdata%\red\,   https://snup.webrootcloudav.com/SkyStoreFileUploader/upload.aspx?MD5=0C75F871F6D72A34CAE0FBC6D60C49A8 0C75F871F6D72A34CAE0FBC6D60C49A8,

CRUSH-2018-11-22-8164.DLL, W32.Adware.Gen, %appdata%\red\,   https://snup.webrootcloudav.com/SkyStoreFileUploader/upload.aspx?MD5=56A73C7D82069CD237B334CEEDE6B6A9 56A73C7D82069CD237B334CEEDE6B6A9,

This is a procedural anti-virus, so it will pick up things it hasn't seen before (definitions-based), see what they do, and put them in quarantine and alert the sysadmin that it's a threat if it does stuff it considers threatening.

Not sure if there is any way Red can be redesigned or fixed to address the newer "procedural" anti-viruses that are popping up like Cylance and Webroot.

**Comment by greggirwin** [comment]
Thanks. Assuming we have to remove anything considered threatening, like writing files through OS APIs, that could be tough. i.e., we can't really design around that. If you use them, please let them know about the false positive. That's about all we can do at this point.

**Comment by aberusugi** [comment]
This is more of an inquiry, since I'm curious... If Red is considered portable, why does it need to drop an EXE and DLL in %appdata%\red? I don't see similar behavior from other portable versions of software. Or have I misunderstood "portable" in this sense? Or is the philosophy of software portability only being applied to the software developed using Red, and not the compiler itself?

**Comment by 9214** [comment]
@aberusugi currently, when you launch the toolchain for the first time, two things happen:

1. Compilation of GUI/CLI console (REPL);
1. Compilation of compression library. 

So, what Red "drops" into `AppData` is driven by necessity: **(1)** by definition is a gateway to Red interpreter, **(2)** is used for packing [RedBin](https://doc.red-lang.org/en/redbin.html) using custom CRUSH algorithm — each compiled binary needs to contain the whole language runtime in order to cope with Red's highly dynamic nature; this compression is what triggers false-positives in AVs with bad heuristics. If you use `--no-compress` with UPX then everything is fine.

> self-compiler is not coded in Red

Both Red → Red/System and Red/System → native compilers are written in Rebol2, which is 90% compatible with Red. This is a consequence of the bootstrapping phase, not related to this issue your questions at all. Both Red toolchain and binaries compiled with it are stand-alone and portable, I'm not sure what makes you think otherwise.

---

In the future, please use community chat for such inquiries.
