### ISSUE TITLE
compiler does not recognize some CHAR! values as valid

### ISSUE THREAD

**Issue by 9214** [red/red#4565]
**Describe the bug**
The compiler chokes on some of the `char!` literals as syntactically invalid. Possibly related: https://github.com/red/red/issues/2870.

**To reproduce**
Compile the script below:
```red
Red [] #""
```
```red
*** Syntax Error: Invalid issue! value
*** in file: ...
*** line: 1
*** at: {""}
```

Non-exhaustive list of other `char!` literals that trigger the same error: `#"^()" #"^(A)"`.

**Expected behavior**
I expect the script to be compiled and `#""` to represent NUL character as it does in the interpreter.

**Platform version**
37366bb, W10.

**Comment by greggirwin** [comment]
I think `#""` should be an error, always. I doubt it will break any old R2 code, and R3 doesn't allow it, but mainly it's an exception that makes no sense because a character always has to be something. Admittedly, in C contexts it's a string terminator, but still not a zero width character. :^) Same for `#"^()"`. The part in the parens has to define a codepoint. `#"^(A)"` _could_ work, as it's a valid hex number. The downside is that it's then inconsistent with `AAh` notation in Red, where at least 2 digits are required. That opens another question, but I don't think we need to support that syntax for codepoints. I'm mixed on it in general for Red, but it's very useful in R/S. So, for Red it's nice that `(A)` is like `^A`, but it may be more consistent to require at least 2 digits. Maybe @meijeru will weigh in.

**Comment by meijeru** [comment]
The one-hexdigit problem has been solved by the fast lexer now, therefore issue #2671 may be closed. I think the argument from hex number notation (`AAh`) is irrelevant since that notation is to be replaced anyhow. Therefore 1 to 6 hex-digits inside the parens is a good rule for me. As for `#""`, I am in agreement that it should be an error.

**Comment by 9214** [comment]
https://github.com/red/red/blob/4e9d770c92c629a94f0235a4b62181a0ff6f40cc/runtime/lexer.reds#L1271

**Comment by greggirwin** [comment]
Seems `#""` only appears in ~8 tests in the Red code base.

@dockimbel can we remove this null char shortcut, or do you have a strong reason to keep it?

**Comment by greggirwin** [comment]
`#"^()"` doesn't appear anywhere, even in tests. `scan-escaped-char` doesn't have a special check for it, so `load-char` might be the place to make it clear that's an error too.

**Comment by 9214** [comment]
```red
>> rebol/version
== 2.101.0.3.1
>> #"^()"
== #"^@"
```

**Comment by greggirwin** [comment]
I don't know what that means @9214. R3 allows it, yes, but R2 does not. My point is that it isn't used anywhere in Red today and I don't think we need to support it. Can you think of a reason we should?

**Comment by dockimbel** [comment]
@greggirwin The only reason it's in Red is for Rebol compatibility. I don't see any good reason to support it in general.
