### ISSUE TITLE
Regression: body-of action/native/op does not work anymore

### ISSUE THREAD

**Issue by meijeru** [red/red#4597]
red/REP/51 was granted by #4289
expected:
```
>> load rejoin [body-of :now reflect :negate 'body]
== 9214
```
currently:
```
>> load rejoin [body-of :now reflect :negate 'body]
*** Internal Error: reserved for future use (or not yet implemented)
*** Where: reflect
*** Stack: load rejoin empty? body-of  
```

**Comment by 9214** [comment]
@meijeru the PR was never merged, so it's not a regression.

**Comment by meijeru** [comment]
(1) do you have info on why it wasn't merged? (2) `op!` seems a logical extension (need to check though whether the op was created from a native or action)

**Comment by 9214** [comment]
@meijeru 
1. Nope.
1. `op!` can return ID of a `native!`/`action!` as an `integer!`, or body of a `function!`/`routine!` as a `block!`; it's a bit problematic though, because that doesn't tell you from where the result came from: is ID from native or action, is body block from function or routine? As of now, there's no way to check `op!`'s "parent" in userspace.

**Comment by meijeru** [comment]
(1) pity! (2) I understand
