### ISSUE TITLE
Agree on casing to avoid confusion

### ISSUE THREAD

**Issue by maksumic** [red/red#4642]
In the `github.com/red/red` root directory there are two directories with different casing styles:
- libRed
- quick-test

Either use "camelCase" *or* "hyphen-ing"

**Comment by 9214** [comment]
@maksumic that sounds a bit too pedantic and doesn't provide any rationale for the change. Can you elaborate on what you find confusing?

[`libRed`](https://www.red-lang.org/2017/03/062-libred-and-macros.html) follows the common convention to prepend `lib` prefix to the name of a shared library, which is named `Red` because that's the name of the programming language. Moreso, `lib` suffix is required by the GCC linker (e.g. `gcc -o foo foo.c -lRed` will search for `libRed`).

`quick-test` is a testing framework that Red uses, which is written in Rebol/Red and follows the naming convention of the language (lowercase, hyphenating).

**Comment by maksumic** [comment]
I'm new to Red and newcomers usually look at "authoritative" code (like the `github.com/red/red` repo) for styling guidance. Another rationale is consistency. But, I didn't know the GCC linker requires the `lib` prefix.

**Comment by 9214** [comment]
@maksumic OK, understood. We have the official [coding style guide](https://github.com/red/docs/blob/master/en/style-guide.adoc) which should answer most of your questions. If you need any help getting started with Red, don't hesitate to drop by our [community chat](https://gitter.im/red/red/welcome).
