### ISSUE TITLE
[Regression] GUI Console is in some kind of mourning lately?

### ISSUE THREAD

**Issue by hiiamboris** [red/red#4825]
**Describe the bug**

It insists on using darker shades of whatever background color I'm choosing after restart:
<img src=https://i.gyazo.com/1d46d425b1aef064171f149bb47af003.gif width="400"></img>
The color is OK after re-setting it in settings dialog, then it becomes grayish after restart again. Every time.

**Expected behavior**

Joyful background with smileys jumping around.

**Platform version**
```
>> about
Red 0.6.4 for Windows built 9-Feb-2021/20:31:32+03:00 commit #18bc5f7
```
I have a build `red-28jan21-bae0c3400` that is not yet affected so it's recent

**Comment by greggirwin** [comment]
Funny ticket title. :^) D2D related perhaps?

**Comment by greggirwin** [comment]
However, I don't see that behavior here on Win10.

**Comment by toomasv** [comment]
Me neither (W10).

**Comment by hiiamboris** [comment]
Can't say. Need to build all commits in the past week to pinpoint it ;)

**Comment by hiiamboris** [comment]
I can say now. The exact commit that causes this regression is https://github.com/red/red/commit/022fa350256f3ddb71dba10bbb3b8d0940095caf 
I have not the slightest idea what it has to do with the GUI console, but I double checked - that's the culprit.
):

**Comment by qtxie** [comment]
@hiiamboris Is the `gui-console-ctx/console/color` correct after restart?

**Comment by hiiamboris** [comment]
![](https://i.gyazo.com/0ed59c00713b0aa562255818ad677447.png)
I made a screenshot so you can see the rendered color does not match the tuple.

**Comment by 9214** [comment]
@hiiamboris is there anything suspicious in `%APPDATA%/Roaming/Red/Red-Console/console-cfg.red`?

**Comment by hiiamboris** [comment]
@9214 It was the first thing that I checked.. but no nothing suspicious. And if I delete the config, console runs with proper background color, then upon restart it saves the config and loads itself with a wrong color again.

**Comment by qtxie** [comment]
If the saved value in console-cfg.red was correct, then something wrong happened on loading part.

**Comment by 9214** [comment]
`black` of a healthy person:
```
02D8B59C: 00180027 00000000  00000000 00000000  '.?.............
```
`black` of a smoker:
```
02D8B59C: 00180027 41000000  6FDDC324 4BFE4E03  '.?....A$??o?N?K
```
The upshot is that `tuple!` value slot gets corrupted.
```red
>> black == gui-console-ctx/console/color
== true
>> black =? gui-console-ctx/console/color
== false
```

And the issue goes away if the GUI console is compiled with GDI+ compatibility.

**Comment by hiiamboris** [comment]
Could it be that Redbin somehow loads junk into unused bytes (after tuple/size), and then D2D uses 4th byte as opacity even though tuple is of size=3 only?

**Comment by 9214** [comment]
@hiiamboris if it's a normal `load` (since console config is stored in plaintext) then that's lexer's doing, which IMO is unlikely. It looks like the color value (`000000` in our case) is overwritten on top of an already trashed slot.

Another observation: make the background color something like `255.255.255.255.255.255.255.255.255.255.255.255` thru console settings, then try to scroll the console history. Don't know if it's related or not.

![image](https://user-images.githubusercontent.com/15716466/109436822-c60a3800-7a21-11eb-8d70-18bee69d94d5.png)

Ẇ̶̢̨̢͕̺̠̼̣̫̺͆͂̾̀̽͐̐̾̾̽̓̀̆͌͘̚͝͝͝ͅḧ̸͉̜͔̠͇̯̣͎̭̞̤̟̩̻̫̩̼͚̞̙́̒̎̂͗̓̓̿͛͒̎̏̿̀́͑̀͜͠͠͝͠å̵̢̹̹̻͇͉̮͍̳̞͆́̿̍̀͌̇̈́̽͋̉̆́͝͝͝t̵̢̢̘̫̯͐̔̽̎̑̄̈͋̇̈̄̏̐̾̈̚̕̕͝͝ ̶̛͙̜͇͓̹̎̊̍̍̍͌͂̃͒͒́̆̒̈́̀͂͗̾̿ͅh̴̛̘͙̜͖́͂̔̽̚ͅȧ̶̢̻͐̓́̔̚v̴̡̨̡̢̛̬̱̞͕̱̠͈͇̦̮̪̩͕̻̳̔̀͐̍̍̂̿͗̊͌͂̆́̄͊̅͘͠͠e̷̡̟̪̥̘͈͙͆̒͛̈͘͜ ̶̧̘͔̩̠͔͎͈̺̤̣̇̃̍̌̈̾̎̾͒́̀͘͝͝͠Ĩ̶͍͇̯̗̜͚̭̣̟̫̱̳̗͜ ̷̲̜̘͙̣̩̹͓̟̣̖͋̔̒̋̌̌͆̓̇̌̏͋̅͑͌͊̀̏̈́͠͝ḓ̴̛̛̘͕̝̏̔͋̓̔̌́̊͐̆̆̈́͌̓̀̓͝͠͝o̸͙͍͔͕̬̗̰̦̮͚̰̼̅̀́̈́̽͌̊̐̀͛̈͠͝͠n̵̡̡͈̱̪͙̭̙̼̫̜̔̇́̓̈̑͂̃̈͆̀è̷̜͙̜̦͖̜͔͔͔̥̬̤͍̹̌̉̓͑͜͠ ̵̨̛̪͕͗͂̋̐̋̈̿̉̑̕̚̕̚ơ̸̺̍̈͂̍̋͒̋̒̉̐̅̎̀͝͝h̶̛̛̦̤̥̹̞͕͚̔̂́́̽͐̒́̍͆̃̏̅͝͝ ̴͕̼͓̫͔̬̤͙͚̭͛͆̓̋͊̍̓̀̏̐͐̂̽̇͜ͅg̸̖͉̮̭̳͇̰̘̤̹̜̝̅͒͆̆̄ͅͅơ̸̦͍̮̰̖̎̌̅̇̆́̈́̂̄̔̎́̊̓͌̀̃̚͠͠d̶͓̰̜̠̱̪̭͖̝̭̿̍̉͐͑̋́̔̽͗́̂̈́̋̎͒̈́̓̾͝ ̶̨̼͇̬̗͔̺̯̜̠͎̼͔̩͕̻͓̜̟̙̯̆́͂̑̾̄͋̈̔͛͠h̷̝̖̼͕̤̅̌̇͐̅̄́̎͘̕e̵̜̳͔͙̽̐̀͒̄̂̇̑̋͒̐̀̔́͠͝ ̴̧͓̟͍͂̿̉̍̎̈́̈̆͐̆̿̽̂̋̿̍͋͝͝c̵̢̧̯̥͕͓͚̰̼̝̆̀̍̓͜ǫ̴̢̡̧̛̛̛̹̰͚͙͙̜͎̯̪̪͇̭̆͆͐͒̈́̎̀̔̈̀̽̏̂͝m̸̹̤̿̅́̾̀͋̏̔̆͌̄̎͆̽̍́̈́͘e̷̬̹̠͇̺̭͉̖̮̞̥̜̪̘̍͂͛͐s̵̢̛͈̮̝͚̙̰͕͚̩̘̺͎̀̇͂͂̓̑͌̃̋̄̌̎̾͗̽͑̇̚̚͝,̴͍̩͈͙̟͎͚̥͒̃̏̓̉͗̓͘ ̷̧̘͚͉̲͈̝̼̻̻̳̟͖͆̎̈́̍̿̌̈́͗̍̇͐̔̐̄͌̂̚͘̕͝͝H̸̛̰̭͑͗̉̈́̔̾̅͘͝E̶̢̛͚͉͇̭̯̹̜̳̳̼̗̎̈͋̈́̈̓͊̅̋̇̿̔͂̿̀̕͠ ̸̨̢͕̻̞͍̠̱͍̝̭͙̫̺̰͋̄̓͘C̷̨̤̝̖͓͍̤̲̭͆̏͐̓͛̽͐̄̍ͅȮ̴̡̳͙̤̠̮̤͕̤̲͍͉̈́M̴̢̛̹̻͔̹̩̯̥̣̼̜̯̹͌͊͊́̒͋̏͜ͅȨ̸̻̗͚͔̯͇̦̘̲̥̯̯̰̓̈́̓̉̓͑̑̀̉͛̍̓̏̅͛͗̂̑͘͝S̷̛͇͙͍̯̯̘͖̻̱̜͈͔̬̺͕̅͋́͊̈́͐̎̅̓̋͌͒͑̽̐̌͘͝!̸̞͙̘̠̭̜̩͈͈͆̇̐̓̌̍̑͊́̕

**Comment by qtxie** [comment]
> ![](https://camo.githubusercontent.com/0cfdd9e52fa706a163103bf0646f5fc214b6bacdfb5fdb5f7b5987fb79fed2bc/68747470733a2f2f692e6779617a6f2e636f6d2f30656435396330303731336230616135363232353538313861643637373434372e706e67)
> I made a screenshot so you can see the rendered color does not match the tuple.

So the color tuple in console-cfg.red was `255.255.255`, then it's loaded as `253.246.227` after restarted the console? That's really weird.

**Comment by qtxie** [comment]
> Another observation: make the background color something like 255.255.255.255.255.255.255.255.255.255.255.255 thru console settings, then try to scroll the console history. Don't know if it's related or not.

That's because `255.255.255.255` is full transparent background color. Seems D2D cannot handle it correctly.

**Comment by qtxie** [comment]
> Could it be that load somehow loads junk into unused bytes (after tuple/size), and then D2D uses 4th byte as opacity even though tuple is of size=3 only?

Yes. It's a problem. The new lexer does not zeroed all the unused bytes.

**Comment by hiiamboris** [comment]
> 253.246.227

No. It was 253.246.227, and loaded as such (properly), but shows gray 179.174.160 (apparently due to hidden alpha channel)

**Comment by hiiamboris** [comment]
The fix works for me.

**Comment by qtxie** [comment]
No issue in the lexer.

**Comment by 9214** [comment]
> No issue in the lexer.

```red
>> 1.2.3 =? 1.2.3
== false
```

**Comment by hiiamboris** [comment]
@9214 nice catch! would you open a separate issue for that?

**Comment by hiiamboris** [comment]
Thanks. Closing this one then.
