### ISSUE TITLE
Money accessors don't implement write support

### ISSUE THREAD

**Issue by hiiamboris** [red/red#4908]
**Describe the bug**

No effect, not even an error:
```
>> system/catalog/accessors/money!
== [code amount]
>> m: USD$1

>> m/amount: 2
== $1.00
>> m/amount: $2
== $1.00
>> m
== USD$1.00

>> m/code: 'EUR
== USD
>> m
== USD$1.00
```

**Expected behavior**

Successful change & return of new code and amount.

**Platform version**
```
Red 0.6.4 for Windows built 12-May-2021/6:12:03+03:00  commit #cebd5b9
```

**Comment by greggirwin** [comment]
I don't know if @9214 and @dockimbel used money as an experiment, but it alias's `function!` as `accessor!`, which no other type does. Makes it clean in use, but is read only for property values. To me "access" implies read/write, but maybe better to keep the changes minimal right now, as that shouldn't be hard to support. Just check for `value` in `eval-path` and assign through internal helpers.

**Comment by meijeru** [comment]
In the spec document this read-only feature is implicitly described since in [section 5.6.2](https://github.com/meijeru/red.specs-public/blob/master/specs.adoc#selection-by-key) there is no explanation for setting a component of a `money!` value. Should this be made explicit or will the read-onliness be changed anyhow? I find @greggirwin 's comment not very enlightening.

**Comment by dockimbel** [comment]
> But I can't think of a reason why you wouldn't want them to be mutable.

We made `money!` values immutable because they are in the same class as other numbers that are immutable like integers and floats (even if `money!` is not part of `number!` typeset, to avoid implicit conversions). It's a number with a unit (we should have a more versatile `unit!` type in the future). The path accessors are just for convenience, to avoid adding new accessor functions specifically for that. Changing a money's unit directly can be dangerous (as it's proabably related to real-world money), so an explicit conversion to a new value is preferable.

**Comment by hiiamboris** [comment]
In such case I expect an error message shown instead of silent failure.

**Comment by greggirwin** [comment]
If not writable, certainly it needs to report an error. I'm OK with `code` being read-only, and we can update the docs and specs accordingly.

@dockimbel, assuming `m: $1`,  how is `m/amount: 2` more dangerous than `m: m + 1` ? You can't have references to money values where someone could change it out from under you.

On a related note, we should disallow adding percents to money values, or decide if they should be "smart" and base it on the amount, rather than treating it as a float.

**Comment by dockimbel** [comment]
> In such case I expect an error message shown instead of silent failure.

Agreed.

**Comment by hiiamboris** [comment]
What about pairs and tuples? They are single-cell values yet modifiable using accessors.

**Comment by dockimbel** [comment]
They are multi-dimensional numbers. Integer, floats, money are 1-dimensional scalar values.

**Comment by hiiamboris** [comment]
I see. Well, from reactivity's standpoint it's even better if money is read only.

**Comment by greggirwin** [comment]
OK, let's go with the error plan for now. @toomasv has done quite a lot of R&D on a `quantity!` dialect, but of course the literal form for those is the big question.

**Comment by greggirwin** [comment]
https://github.com/toomasv/units

**Comment by greggirwin** [comment]
I also noted for Toomas that this starts moving us more into symbolic computing, where Wolfram is the reference standard. Considering their wealth of data, we shouldn't ignore that area.
