### ISSUE TITLE
[R/S] Compiler blames the wrong operator in an expression

### ISSUE THREAD

**Issue by hiiamboris** [red/red#4925]
**Describe the bug**
```
Red/System []

a: as byte-ptr! 100
b: as int-ptr! 60
;probe a - b
probe a - b >>> 2
```
`probe a - b` is valid code
In `probe a - b >>> 2` `as-integer` cast is forgotten, should be `(as-integer a - b) >>> 2`

What compiler says instead is confusing:
```
Compiling to native code...
*** Compilation Error: argument type mismatch on calling: -**
*** expected: [number!], found: [pointer! [byte!]]
*** in file: %/D/devel/red/red-src/red/2.reds
*** at line: 6
*** near: [- a b 2]
```
Why it blames the subtraction?

**Expected behavior**

To the point error message, e.g. `>>> expected integer as left operand, found pointer`, or something.

**Platform version**
```
Red 0.6.4 for Windows built 4-Jul-2021/2:04:09+03:00  commit #1e4fb1b
```

**Comment by dockimbel** [comment]
> Why it blames the subtraction?

It blames the `- a b` expression, which is the first argument (left operand) of the `>>>` operator.  The compiler rewrites the input code for infix operators to make them all prefix, so that internally, the compiler sees the expression as `>>> - a b 2`, hence the `near: [- a b 2]`, which points to the first faulty argument.
