### ISSUE TITLE
`make map! length` carries an unpractical meaning

### ISSUE THREAD

**Issue by hiiamboris** [red/red#5547]
**Describe the bug**

I was always doubting, whether `make map! 3` allocates 3 key/value pairs or 1.5 key/value pairs.
Running tests I'm seeing that `make map! 6` allocates exactly the same amount of RAM as `make map! [a 1 b 2 c 3]` so the second hypothesis is true.
But:
- it is not useful to allocate odd number of slots in a map - the last slot is going to be wasted at best
- it is not consistent with `length?` behavior (`length? #[a 1 b 2 c 3] == 3` not `6`)

**Expected behavior**

I propose `make map! n` to have a meaning of allocating for `n` key/value pairs.

**Platform version**
```
Red 0.6.5 for Windows built 16-Aug-2024/11:34:58+08:00  commit #dbc93da
```

**Comment by dockimbel** [comment]
No objection against such change.

**Comment by greggirwin** [comment]
It also aligns with throwing an error if a map spec has an odd number of elements. If `make <size>` doesn't use k-v pairs as the size, odd sizes should throw an error.

**Comment by dockimbel** [comment]
After making that change with error raising on odd requested sizes, the tests are not passing anymore. It chokes on dynamic cases like [this one](https://github.com/red/red/blob/master/environment/codecs/CSV.red#L298) in the CSV codec.

**Comment by greggirwin** [comment]
It *is* a breaking change, so we need to note that.

**Comment by greggirwin** [comment]
Will look at the code, and we can mention it for @rebolek as well, to make sure it's not trickier than it looks.

**Comment by GiuseppeChillemi** [comment]
Why can't the LENGHT rapresent K/V pairs, so MAKE MAP 3 is 3 pairs? I think @hiiamboris was asking for this.

**Comment by greggirwin** [comment]
That's the change that is likely coming. @dockimbel just noted code that breaks because of it. And the `length` there isn't necessary by any means, just a nice (possible) optimization. Would have to test to see if it is an actual win.

**Comment by dockimbel** [comment]
@greggirwin I'm wondering if raising an error in such case will not make dynamic cases significantly more complicated than needed. You would need to systematically insert an extra line like: `if odd? length [length: length + 1]`

**Comment by greggirwin** [comment]
If the new behavior, where N = number of k-v pairs is used, then it doesn't need to raise an error on `odd? N`. If that change isn't made, then we have to decide, because dynamic cases may allocate one too few slots, or an extra depending on how they calc it. Not the end of the world either way, but needs to be explained.

**Comment by greggirwin** [comment]
What happens with the N=k-v change is that no code breaks, but twice as many slots as needed are allocated, so code *should* be fixed, not for the waste but because the allocation logic will look wrong.

**Comment by hiiamboris** [comment]
> What happens with the N=k-v change is that no code breaks, but twice as many slots as needed are allocated, so code _should_ be fixed, not for the waste but because the allocation logic will look wrong.

*Should* code be fixed, or *will* it be fixed? Because the only case where it matters I find in Red is in CSV codec, where the logic expects the number of k/v pairs: 
https://github.com/red/red/blob/adf4bdc79bab2c87fa7f9e35485ad2b35226c0eb/environment/codecs/CSV.red#L298-L301

**Comment by GiuseppeChillemi** [comment]
Please note that other than `MAP!`, `OBJECT!` also has `K/V` pairs, so it should return the same value too when queried:

```
>> length? make object! [a: 22]
*** Script Error: length? does not allow object! for its series argument
*** Where: length?
*** Near : length? make object! [a: 22]
*** Stack:  
```

**Comment by greggirwin** [comment]
We will certainly fix teh CSV code, but there is other code in the wild, albeit not much in our case. I tend to think in those terms, as I value other people not breaking *my* code. :^)

**Comment by greggirwin** [comment]
@GiuseppeChillemi indeed. Adding it as a convenience for maps, because of the implementation leads to this consistency question. However, then we have to ask about `[foreach clear find remove]`. `Length?` is read-only, so should be fine. `Remove` isn't possible with how objects work today, unless we use `/key` with it and make it return a copy of the object. That's enough different that I think we leave that to a mezz for now. `Clear` only works for map heads, so it's all or nothing. Objects can't remove words, so the closest thing it could do there is set all values to `none`. That might be OK, as it's the same as `set <obj> none`, and is clearer, as it won't be confused with setting the object ref to `none`. `Find` only works for keys in maps, so could do the same for words in objects. We added func support to `in`, so this is probably also OK. It would be the equivalent of `in`. Question of whether it should be bound or not.

**Comment by GiuseppeChillemi** [comment]
I would not add support for `REMOVE` until we can modify objects and for me it is not ok for `CLEAR` to set to `none` everything as once you fix this working it will be difficult to change when keys could be removed. `Clear` will be useful to keep the reference to the `object!` everywhere it is and change its content. `Set` already does a good job for this.

**Comment by dockimbel** [comment]
I've pushed the change. I've changed my implementation to avoid raising errors, so that all the tests are passing fine. The CSV code (probably also in other places) would still need minor change to adjust to the new rule and avoid allocating double sizes.

**Comment by hiiamboris** [comment]
> The CSV code (probably also in other places) would still need minor change to adjust to the new rule and avoid allocating double sizes.

As noted above, it expected double size, so it is now just working and no fix is needed.

**Comment by greggirwin** [comment]
Docs updated. In looking at it, I noticed that block and hash have different sections, so simplified the map change. At some point we should normalize things.
