### ISSUE TITLE
Compiled SWITCH does not honor multiple case values

### ISSUE THREAD

**Issue by hostilefork** [red/red#611]
In the Red interpreter (and in Rebol) you get "x is either a one or a two" if you write:

    x: 2
    switch x [
        1 2 [print "x is either a one or a two"]
    ]

But if you use Red's `-c` option to compile this code, it will not print anything.  Changing x to 1 will print the message, however.

Using "0.4.1, 13-Dec-2013/23:19:35-5:00"

**Comment by iArnold** [comment]
I suggested /block refinement for the blocks-as-key handling. @ dockimbel countered this with /only refinement as option. Personally I feel /only says little about the way in which the handling differs, /block is more descriptive.
There could be also an alternative for switch with blocks-as-key: 'FORK

I want to mention some other point to the 'switch and that is I like Red/System way of dealing with the default better than the /default Red and Rebol are using.

I sincerely hope this issue will be fixed soon, since my projectcode makes heavily use of these multiple case situations and the rewriting makes them unpretty code.
