### ISSUE TITLE
object! expansion missing

### ISSUE THREAD

**Issue by Kaj-de-Vos** [red/red#618]
red>> append context [] [a: 'b]

**\* Script error: action 35 not defined for type: 30

R3:

> > append context [] [a: 'b]
> > == make object! [
> >     a: 'b
> > ]

This is inefficient, because when constructing an object by iterating over some input, you first have to construct an intermediate spec block to construct the object from.

**Comment by PeterWAWood** [comment]
Following the introduction the [Red REP repository for enhancements and wishes](https://gitter.im/red/red?at=5adfeed527c509a7744a3dc8), this issue is being closed.

If you believe that your wish is still valid, please open a new issue for it in the new [red/REP repo](https://github.com/red/REP). It would help if you could include a link to this issue when opening an issue in the REP repository.
