### ISSUE TITLE
WISH: support for inlining functions during compilation.

### ISSUE THREAD

**Issue by Oldes** [red/red#896]
As the title says, it would be nice to have inlined functions to increase performance. Maybe such functions could be cached as precompiled and so be part of the work on improvements of the compilation time.

It's not top priority, but I think it is good to have it in mind.

**Comment by PeterWAWood** [comment]
Following the introduction the [Red REP repository for enhancements and wishes](https://gitter.im/red/red?at=5adfeed527c509a7744a3dc8), this issue is being closed.

If you believe that your wish is still valid, please open a new issue for it in the new [red/REP repo](https://github.com/red/REP). It would help if you could include a link to this issue when opening an issue in the REP repository.
