### ISSUE TITLE
Finalize support for Intel Registers

### ISSUE THREAD

**Issue by OneArb** [red/red#958]
system/cpu/eax: 0
system/cpu/eax: system/cpu/eax - 2 ; -2 as expected

system/cpu/eax: system/cpu/eax - system/cpu/eax ; -206849

system/cpu/edx: 2
system/cpu/eax: 0
system/cpu/eax: system/cpu/eax - system/cpu/edx ; 0

on Windows

**Comment by PeterWAWood** [comment]
Following the introduction the [Red REP repository for enhancements and wishes](https://gitter.im/red/red?at=5adfeed527c509a7744a3dc8), this issue is being closed.

If you believe that your wish is still valid, please open a new issue for it in the new [red/REP repo](https://github.com/red/REP). It would help if you could include a link to this issue when opening an issue in the REP repository.
